Improved CAD-score wrapper script.

diff --git a/voronota-cadscore b/voronota-cadscore
--- a/voronota-cadscore
+++ b/voronota-cadscore
@@ -40,12 +40,12 @@ do
 	esac
 done
 
-if [ -z "$INFILE_TARGET_PDB" ] || [ -z "$INFILE_MODEL_PDB" ] || $HELP_MODE
+if [ -z "$INFILE_TARGET_PDB$INFILE_TARGET_CONTACTS" ] || [ -z "$INFILE_MODEL_PDB$INFILE_MODEL_CONTACTS" ] || $HELP_MODE
 then
 cat >&2 << EOF
 Script parameters:
-    -t input_target_file.pdb
-    -m input_model_file.pdb
+    [-t input_target_file.pdb]
+    [-m input_model_file.pdb]
     [-T input_target_contacts_file]
     [-M input_model_contacts_file]
     [-a output_residue_scores_on_target_file.pdb]
@@ -65,23 +65,42 @@ fi
 command -v voronota &> /dev/null || { echo >&2 "Error: 'voronota' executable not in binaries path"; exit 1; }
 command -v voronota-resources &> /dev/null || { echo >&2 "Error: 'voronota-resources' executable not in binaries path"; exit 1; }
 
-if [ ! -s "$INFILE_TARGET_PDB" ]
+if [ -n "$INFILE_TARGET_PDB" ] && [ ! -s "$INFILE_TARGET_PDB" ]
 then
-	echo >&2 "Error: input target file does not exist or is empty"
+	echo >&2 "Error: input target file does not exist"
 	exit 1
 fi
 
-if [ ! -s "$INFILE_MODEL_PDB" ]
+if [ -n "$INFILE_TARGET_CONTACTS" ] && [ ! -s "$INFILE_TARGET_CONTACTS" ]
 then
-	echo >&2 "Error: input model file does not exist or is empty"
+	echo >&2 "Error: input target contacts file does not exist"
+	exit 1
+fi
+
+if [ -n "$INFILE_MODEL_PDB" ] && [ ! -s "$INFILE_MODEL_PDB" ]
+then
+	echo >&2 "Error: input model file does not exist"
+	exit 1
+fi
+
+if [ -n "$INFILE_MODEL_CONTACTS" ] && [ ! -s "$INFILE_MODEL_CONTACTS" ]
+then
+	echo >&2 "Error: input model contacts file does not exist"
 	exit 1
 fi
 
 readonly TMPDIR=$(mktemp -d)
 trap "rm -r $TMPDIR" EXIT
 
-cp $INFILE_TARGET_PDB $TMPDIR/target
-cp $INFILE_MODEL_PDB $TMPDIR/model
+if [ -s "$INFILE_TARGET_PDB" ]
+then
+	cp $INFILE_TARGET_PDB $TMPDIR/target
+fi
+
+if [ -s "$INFILE_MODEL_PDB" ]
+then
+	cp $INFILE_MODEL_PDB $TMPDIR/model
+fi
 
 if [ -s "$INFILE_TARGET_CONTACTS" ]
 then
@@ -95,31 +114,34 @@ fi
 
 for WORKFILE in $TMPDIR/target $TMPDIR/model
 do
-	cat $WORKFILE \
-	| voronota get-balls-from-atoms-file \
-	  --annotated \
-	  --radii-file <(voronota-resources radii) \
-	| voronota query-balls \
-	  --drop-adjuncts \
-	  --drop-altloc-indicators \
-	> $WORKFILE.balls
-	
-	if [ ! -s "$WORKFILE.contacts" ]
+	if [ -s "$WORKFILE" ]
 	then
-		cat $WORKFILE.balls \
-		| voronota calculate-contacts \
+		cat $WORKFILE \
+		| voronota get-balls-from-atoms-file \
 		  --annotated \
-		| voronota query-contacts \
-		  --match-min-seq-sep 1 \
-		  --no-solvent \
-		| voronota query-contacts \
-		  --match-first 'A<C>' \
-		  --match-second 'A<N>' \
-		  --match-max-seq-sep 1 \
-		  --match-max-dist 1.6 \
-		  --invert \
-		| awk '{print $1 " " $2 " " $3}' \
-		> $WORKFILE.contacts
+		  --radii-file <(voronota-resources radii) \
+		| voronota query-balls \
+		  --drop-adjuncts \
+		  --drop-altloc-indicators \
+		> $WORKFILE.balls
+	
+		if [ ! -s "$WORKFILE.contacts" ]
+		then
+			cat $WORKFILE.balls \
+			| voronota calculate-contacts \
+			  --annotated \
+			| voronota query-contacts \
+			  --match-min-seq-sep 1 \
+			  --no-solvent \
+			| voronota query-contacts \
+			  --match-first 'A<C>' \
+			  --match-second 'A<N>' \
+			  --match-max-seq-sep 1 \
+			  --match-max-dist 1.6 \
+			  --invert \
+			| awk '{print $1 " " $2 " " $3}' \
+			> $WORKFILE.contacts
+		fi
 	fi
 done
 
@@ -133,7 +155,7 @@ cat $TMPDIR/model.contacts \
 | awk '{print $2}' \
 > $TMPDIR/global_cad_score
 
-if [ -n "$OUTFILE_RESIDUE_SCORES_ON_TARGET" ]
+if [ -n "$OUTFILE_RESIDUE_SCORES_ON_TARGET" ] && [ -s "$TMPDIR/target.balls" ]
 then
 	mkdir -p $(dirname $OUTFILE_RESIDUE_SCORES_ON_TARGET)
 	cat $TMPDIR/target.balls \
@@ -146,7 +168,7 @@ then
 	> /dev/null
 fi
 
-if [ -n "$OUTFILE_RESIDUE_SCORES_ON_MODEL" ]
+if [ -n "$OUTFILE_RESIDUE_SCORES_ON_MODEL" ] && [ -s "$TMPDIR/model.balls" ]
 then
 	mkdir -p $(dirname $OUTFILE_RESIDUE_SCORES_ON_MODEL)
 	cat $TMPDIR/model.balls \
