Added export LC_ALL=C in bash wrappers to avoid sort/join errors.

diff --git a/voronota-cadscore b/voronota-cadscore
--- a/voronota-cadscore
+++ b/voronota-cadscore
@@ -42,6 +42,19 @@ exit 1
 }
 
 readonly ZEROARG=$0
+
+if [[ $ZEROARG == *"/"* ]]
+then
+	cd "$(dirname ${ZEROARG})"
+	export PATH="$(pwd):${PATH}"
+	cd - &> /dev/null
+fi
+
+export LC_ALL=C
+
+command -v voronota &> /dev/null || { echo >&2 "Error: 'voronota' executable not in binaries path"; exit 1; }
+command -v voronota-resources &> /dev/null || { echo >&2 "Error: 'voronota-resources' executable not in binaries path"; exit 1; }
+
 INFILE_TARGET_PDB=""
 INFILE_MODEL_PDB=""
 INPUT_FILTER_QUERY_PARAMETERS=""
@@ -169,16 +182,6 @@ if [ -z "$INFILE_TARGET_PDB" ] || [ -z "$INFILE_MODEL_PDB" ] || $HELP_MODE
 then
 	print_help_and_exit
 fi
-
-if [[ $ZEROARG == *"/"* ]]
-then
-	cd $(dirname $ZEROARG)
-	export PATH=$(pwd):$PATH
-	cd - &> /dev/null
-fi
-
-command -v voronota &> /dev/null || { echo >&2 "Error: 'voronota' executable not in binaries path"; exit 1; }
-command -v voronota-resources &> /dev/null || { echo >&2 "Error: 'voronota-resources' executable not in binaries path"; exit 1; }
 
 MD5SUM_COMMAND="md5sum"
 if command -v md5sum &> /dev/null
diff --git a/voronota-contacts b/voronota-contacts
--- a/voronota-contacts
+++ b/voronota-contacts
@@ -32,6 +32,19 @@ exit 1
 }
 
 readonly ZEROARG=$0
+
+if [[ $ZEROARG == *"/"* ]]
+then
+	cd "$(dirname ${ZEROARG})"
+	export PATH="$(pwd):${PATH}"
+	cd - &> /dev/null
+fi
+
+export LC_ALL=C
+
+command -v voronota &> /dev/null || { echo >&2 "Error: 'voronota' executable not in binaries path"; exit 1; }
+command -v voronota-resources &> /dev/null || { echo >&2 "Error: 'voronota-resources' executable not in binaries path"; exit 1; }
+
 INFILE=""
 INPUT_FILTER_QUERY_PARAMETERS=""
 CONTACTS_QUERY_FIRST_PARAMETERS="--match-min-seq-sep 1"
@@ -109,16 +122,6 @@ if [ -z "$INFILE" ] || $HELP_MODE
 then
 	print_help_and_exit
 fi
-
-if [[ $ZEROARG == *"/"* ]]
-then
-	cd $(dirname $ZEROARG)
-	export PATH=$(pwd):$PATH
-	cd - &> /dev/null
-fi
-
-command -v voronota &> /dev/null || { echo >&2 "Error: 'voronota' executable not in binaries path"; exit 1; }
-command -v voronota-resources &> /dev/null || { echo >&2 "Error: 'voronota-resources' executable not in binaries path"; exit 1; }
 
 if $USE_HBPLUS
 then
diff --git a/voronota-voromqa b/voronota-voromqa
--- a/voronota-voromqa
+++ b/voronota-voromqa
@@ -136,6 +136,19 @@ function substitute_ids_in_filename
 
 readonly ZEROARG=$0
 ALLARGS=("$@")
+
+if [[ $ZEROARG == *"/"* ]]
+then
+	cd "$(dirname ${ZEROARG})"
+	export PATH="$(pwd):${PATH}"
+	cd - &> /dev/null
+fi
+
+export LC_ALL=C
+
+command -v voronota &> /dev/null || { echo >&2 "Error: 'voronota' executable not in binaries path"; exit 1; }
+command -v voronota-resources &> /dev/null || { echo >&2 "Error: 'voronota-resources' executable not in binaries path"; exit 1; }
+
 INFILE=""
 REFERENCE_SEQUENCE=""
 INPUT_FILTER_QUERY_PARAMETERS=""
@@ -647,16 +660,6 @@ then
 	PRINT_CLASH_SCORE_OF_CONTACTS_SELECTION=true
 	PRINT_GLOBAL_SCORES_HEADER=true
 fi
-
-if [[ "$ZEROARG" == *"/"* ]]
-then
-	cd $(dirname $ZEROARG)
-	export PATH=$(pwd):$PATH
-	cd - &> /dev/null
-fi
-
-command -v voronota &> /dev/null || { echo >&2 "Error: 'voronota' executable not in binaries path"; exit 1; }
-command -v voronota-resources &> /dev/null || { echo >&2 "Error: 'voronota-resources' executable not in binaries path"; exit 1; }
 
 MD5SUM_COMMAND="md5sum"
 if command -v md5sum &> /dev/null
