Fixed problem with md5 in macOS.

diff --git a/voronota-voromqa b/voronota-voromqa
--- a/voronota-voromqa
+++ b/voronota-voromqa
@@ -626,6 +626,16 @@ fi
 command -v voronota &> /dev/null || { echo >&2 "Error: 'voronota' executable not in binaries path"; exit 1; }
 command -v voronota-resources &> /dev/null || { echo >&2 "Error: 'voronota-resources' executable not in binaries path"; exit 1; }
 
+MD5SUM_COMMAND="md5sum"
+if command -v md5sum &> /dev/null
+then
+	MD5SUM_COMMAND="md5sum"
+else
+	MD5SUM_COMMAND="md5"
+fi
+command -v $MD5SUM_COMMAND &> /dev/null || { echo >&2 "Error: 'md5sum' or 'md5' executable not in binaries path"; exit 1; }
+
+
 if [ -n "$OUTFILE_PLOT" ]
 then
 	command -v R &> /dev/null || { echo >&2 "Error: 'R' command, needed for plotting, is not available"; exit 1; }
@@ -1006,7 +1016,7 @@ fi
 CACHE_MD5=""
 if [ -n "$CACHE_DIRECTORY" ]
 then
-	CACHE_MD5=$(cat $TMPLDIR/balls <(echo "$PROBE_RADIUS" "$TAG_PERIPHERAL_CONTACTS $OPTIONS_FOR_CALCULATING_CONTACTS") | md5sum | awk '{print $1}')
+	CACHE_MD5=$(cat $TMPLDIR/balls <(echo "$PROBE_RADIUS" "$TAG_PERIPHERAL_CONTACTS $OPTIONS_FOR_CALCULATING_CONTACTS") | $MD5SUM_COMMAND | awk '{print $1}')
 	if [ -n "$CACHE_MD5" ]
 	then
 		CACHE_MD5="${CACHE_MD5}.voronota.voromqa"
