Improved file reading in VoroMQA script.

diff --git a/voronota-voromqa b/voronota-voromqa
--- a/voronota-voromqa
+++ b/voronota-voromqa
@@ -76,7 +76,7 @@ EOF
 exit 1
 fi
 
-if [[ $ZEROARG == *"/"* ]]
+if [[ "$ZEROARG" == *"/"* ]]
 then
 	cd $(dirname $ZEROARG)
 	export PATH=$(pwd):$PATH
@@ -86,24 +86,35 @@ fi
 command -v voronota &> /dev/null || { echo >&2 "Error: 'voronota' executable not in binaries path"; exit 1; }
 command -v voronota-resources &> /dev/null || { echo >&2 "Error: 'voronota-resources' executable not in binaries path"; exit 1; }
 
-if [ ! -s "$INFILE" ]
+readonly TMPDIR=$(mktemp -d)
+trap "rm -r $TMPDIR" EXIT
+
+INFILE_CONTENTS=$INFILE
+if [[ "$INFILE" == *"://"* ]]
+then
+	INFILE_CONTENTS=$TMPDIR/downloaded_input_file
+	curl -s "$INFILE" > $INFILE_CONTENTS
+fi
+
+if [ ! -s "$INFILE_CONTENTS" ]
 then
 	echo >&2 "Error: input file does not exist or is empty"
 	exit 1
 fi
 
-readonly TMPDIR=$(mktemp -d)
-trap "rm -r $TMPDIR" EXIT
-
-INPRINTER="cat"
-file $INFILE > $TMPDIR/input_file_type
-if grep "gzip compressed data" $TMPDIR/input_file_type > /dev/null
+INFILE_CONTENTS_EXTRACTED=$INFILE_CONTENTS
+if [[ "$INFILE" == *".gz" ]]
 then
-	INPRINTER="zcat"
+	INFILE_CONTENTS_EXTRACTED=$TMPDIR/extracted_input_file
+	zcat $INFILE_CONTENTS > $INFILE_CONTENTS_EXTRACTED
+	if [ ! -s "$INFILE_CONTENTS_EXTRACTED" ]
+	then
+		echo >&2 "Error: could not extract gzipped file"
+		exit 1
+	fi
 fi
-$INPRINTER $INFILE > $TMPDIR/extracted_input_file
 
-cat $TMPDIR/extracted_input_file \
+cat $INFILE_CONTENTS_EXTRACTED \
 | voronota get-balls-from-atoms-file \
   --annotated $MULTIPLE_MODELS_CHAINS_OPTION \
   --radii-file <(voronota-resources radii) \
@@ -211,7 +222,7 @@ then
 	| voronota x-write-balls-to-atoms-file \
 	  --pdb-output $OUTFILE_CAMEO_RESIDUE_SCORES \
 	  --pdb-output-b-factor rqscore \
-	  --pdb-output-template $TMPDIR/extracted_input_file \
+	  --pdb-output-template $INFILE_CONTENTS_EXTRACTED \
 	> /dev/null
 fi
 
