Enhanced options checking in VoroMQA script.

diff --git a/voronota-voromqa b/voronota-voromqa
--- a/voronota-voromqa
+++ b/voronota-voromqa
@@ -140,6 +140,24 @@ EOF
 exit 1
 fi
 
+if [ -n "$REFERENCE_SEQUENCE" ] && [ -n "$MULTIPLE_MODELS_CHAINS_OPTION" ]
+then
+	echo >&2 "Error: '--reference-sequence' and '--multiple-models' cannot be used together"
+	exit 1
+fi
+
+if [ -n "$OUTFILE_CAMEO_RESIDUE_SCORES" ] && [ -n "$MULTIPLE_MODELS_CHAINS_OPTION" ]
+then
+	echo >&2 "Error: '--output-residue-scores-for-CAMEO' and '--multiple-models' cannot be used together"
+	exit 1
+fi
+
+if [ -z "$REFERENCE_SEQUENCE" ] && [ -n "$OUTFILE_SEQUENCE_ALIGNMENT" ]
+then
+	echo >&2 "Error: '--output-sequence-alignment' cannot be used without '--reference-sequence'"
+	exit 1
+fi
+
 if [[ "$ZEROARG" == *"/"* ]]
 then
 	cd $(dirname $ZEROARG)
