Improved Bash-based scripting environment.

diff --git a/voronota-runscript b/voronota-runscript
--- a/voronota-runscript
+++ b/voronota-runscript
@@ -25,21 +25,20 @@ then
 		export PATH=$(pwd):$PATH
 		cd - &> /dev/null
 	fi
-	TMPLDIR="$(mktemp -d)"
 fi
 
 command -v voronota &> /dev/null || { echo >&2 "Error: 'voronota' executable not in binaries path"; exit 1; }
+command -v voronota-resources &> /dev/null || { echo >&2 "Error: 'voronota-resources' executable not in binaries path"; exit 1; }
 
-coproc VORONOTAPROC { voronota x-run-script --interactive --max-unfolding 0; }
-exec 5<&${VORONOTAPROC[0]} 6>&${VORONOTAPROC[1]}
+coproc VORONOTA_PROC { voronota x-run-script --interactive --max-unfolding 0; }
+exec 5<&${VORONOTA_PROC[0]} 6>&${VORONOTA_PROC[1]}
+
+readonly VORONOTA_PROC_TMPDIR="$(mktemp -d)"
 
 function exit_environment
 {
 	exec 5<&- 6>&-
-	if $NONINTERACTIVE
-	then
-		rm -r "$TMPLDIR"
-	fi
+	rm -r "$VORONOTA_PROC_TMPDIR"
 }
 
 trap exit_environment EXIT
@@ -52,13 +51,25 @@ function vc
 	unset VORONOTAOUT
 }
 
-export -f vc
+function vcq
+{
+	vc "$*" > /dev/null
+}
+
+voronota-resources radii > "$VORONOTA_PROC_TMPDIR/_radii"
+voronota-resources voromqa_v1_energy_potential > "$VORONOTA_PROC_TMPDIR/_voromqa_v1_energy_potential"
+voronota-resources voromqa_v1_energy_means_and_sds > "$VORONOTA_PROC_TMPDIR/_voromqa_v1_energy_means_and_sds"
+vc "setup-loading --radii-file '$VORONOTA_PROC_TMPDIR/_radii'"
+vc "setup-voromqa --potential '$VORONOTA_PROC_TMPDIR/_voromqa_v1_energy_potential' --means-and-sds '$VORONOTA_PROC_TMPDIR/_voromqa_v1_energy_means_and_sds'"
 
 if $NONINTERACTIVE
 then
-	SCRIPTFILE="$TMPLDIR/script.bash"
+	SCRIPTFILE="$VORONOTA_PROC_TMPDIR/_script.bash"
 	cat | egrep -v '^#' > "$SCRIPTFILE"
 	chmod +x "$SCRIPTFILE"
+	export VORONOTA_PROC_TMPDIR
+	export -f vc
+	export -f vcq
 	$SCRIPTFILE "${ALLARGS[@]}"
 fi
 
