Refactored convenience scripts.

diff --git a/voronota-membrane b/voronota-membrane
--- a/voronota-membrane
+++ b/voronota-membrane
@@ -24,6 +24,18 @@ exit 1
 }
 
 readonly ZEROARG=$0
+
+if [[ $ZEROARG == *"/"* ]]
+then
+	cd $(dirname $ZEROARG)
+	export PATH=$(pwd):$PATH
+	cd - &> /dev/null
+fi
+
+command -v voronota &> /dev/null || { echo >&2 "Error: 'voronota' executable not in binaries path"; exit 1; }
+command -v voronota-resources &> /dev/null || { echo >&2 "Error: 'voronota-resources' executable not in binaries path"; exit 1; }
+command -v jq &> /dev/null || { echo >&2 "Error: 'jq' executable not in binaries path"; exit 1; }
+
 INFILE=""
 INPUT_FILTER_QUERY=""
 MEMBRANE_WIDTH="30.0"
@@ -76,17 +88,6 @@ if [ -z "$INFILE" ] || $HELP_MODE
 then
 	print_help_and_exit
 fi
-
-if [[ $ZEROARG == *"/"* ]]
-then
-	cd $(dirname $ZEROARG)
-	export PATH=$(pwd):$PATH
-	cd - &> /dev/null
-fi
-
-command -v voronota &> /dev/null || { echo >&2 "Error: 'voronota' executable not in binaries path"; exit 1; }
-command -v voronota-resources &> /dev/null || { echo >&2 "Error: 'voronota-resources' executable not in binaries path"; exit 1; }
-command -v jq &> /dev/null || { echo >&2 "Error: 'jq' executable not in binaries path"; exit 1; }
 
 if [ ! -s "$INFILE" ]
 then
