Added custom energy resources input functionality to the VoroMQA script.

diff --git a/voronota-voromqa b/voronota-voromqa
--- a/voronota-voromqa
+++ b/voronota-voromqa
@@ -75,6 +75,8 @@ SURFACE_CRAVING_RESIDUES_OUTPUT_PDB=""
 SURFACE_CRAVING_ATOMS_ENERGIES_OUTPUT=""
 SURFACE_CRAVING_DEPTH_VALUE="3"
 ENERGY_MODE="voromqa_v1"
+ENERGY_INPUT_POTENTIAL=""
+ENERGY_INPUT_STATISTICS=""
 NEGLECT_SAS=false
 REINTERPRET_SAS=false
 MORE_LOGGING=false
@@ -243,6 +245,14 @@ do
 		ENERGY_MODE="$OPTARG"
 		shift
 		;;
+	--energy-input-potential)
+		ENERGY_INPUT_POTENTIAL="$OPTARG"
+		shift
+		;;
+	--energy-input-statistics)
+		ENERGY_INPUT_STATISTICS="$OPTARG"
+		shift
+		;;
 	--multiple-models)
 		MULTIPLE_MODELS_CHAINS_OPTION="--multimodel-chains"
 		;;
@@ -346,6 +356,24 @@ fi
 if [ -n "$ADD_HYDROGENS_COMMAND" ]
 then
 	command -v $ADD_HYDROGENS_COMMAND &> /dev/null || { echo >&2 "Error: '$ADD_HYDROGENS_COMMAND' command, requested for adding hydrogens, is not available"; exit 1; }
+fi
+
+if [ "$ENERGY_MODE" != "voromqa_v1" ]
+then
+	echo >&2 "Error: unsupported energy mode '$ENERGY_MODE'"
+	exit 1
+fi
+
+if [ -n "$ENERGY_INPUT_POTENTIAL" ] && [ ! -s "$ENERGY_INPUT_POTENTIAL" ]
+then
+	echo >&2 "Error: no file '$ENERGY_INPUT_POTENTIAL'"
+	exit 1
+fi
+
+if [ -n "$ENERGY_INPUT_STATISTICS" ] && [ ! -s "$ENERGY_INPUT_STATISTICS" ]
+then
+	echo >&2 "Error: no file '$ENERGY_INPUT_STATISTICS'"
+	exit 1
 fi
 
 readonly TMPLDIR=$(mktemp -d)
@@ -573,11 +601,31 @@ then
 	exit 0
 fi
 
+mkdir -p $TMPLDIR/resources
+
+{
+if [ -n "$ENERGY_INPUT_POTENTIAL" ]
+then
+	cat "$ENERGY_INPUT_POTENTIAL"
+else
+	voronota-resources ${ENERGY_MODE}_energy_potential
+fi
+} > $TMPLDIR/resources/energy_potential
+
+{
+if [ -n "$ENERGY_INPUT_STATISTICS" ]
+then
+	cat "$ENERGY_INPUT_STATISTICS"
+else
+	voronota-resources ${ENERGY_MODE}_energy_means_and_sds
+fi
+} > $TMPLDIR/resources/energy_means_and_sds
+
 if [ ! -s "$TMPLDIR/foundation/atom_energies" ]
 then
 	cat $TMPLDIR/contacts \
 	| voronota score-contacts-energy \
-	  --potential-file <(voronota-resources ${ENERGY_MODE}_energy_potential) \
+	  --potential-file $TMPLDIR/resources/energy_potential \
 	  --atom-scores-file $TMPLDIR/foundation/atom_energies \
 	> /dev/null
 fi
@@ -602,7 +650,7 @@ then
 	| tr ';' '_' \
 	| sed 's|c<solvent>\s\+.\s\+\S\+$|c<solvent> . 0.001|' \
 	| voronota score-contacts-energy \
-	  --potential-file <(voronota-resources ${ENERGY_MODE}_energy_potential) \
+	  --potential-file $TMPLDIR/resources/energy_potential \
 	  --atom-scores-file $TMPLDIR/foundation/atom_energies \
 	> /dev/null
 fi
@@ -613,7 +661,7 @@ then
 	| awk '{print $1 " " $2 " " $5 " " $3}' \
 	| tr ';' '_' \
 	| voronota score-contacts-energy \
-	  --potential-file <(voronota-resources ${ENERGY_MODE}_energy_potential | voronota x-simulate-potential-for-membrane-proteins) \
+	  --potential-file <(cat $TMPLDIR/resources/energy_potential | voronota x-simulate-potential-for-membrane-proteins) \
 	  --atom-scores-file $TMPLDIR/foundation/atom_energies \
 	> /dev/null
 fi
@@ -625,7 +673,7 @@ then
 	| awk '{print $1 " " $2 " " $5 " " $3}' \
 	| tr ';' '_' \
 	| voronota x-score-contacts-global-energy-by-cuts \
-	  --potential-file <(voronota-resources ${ENERGY_MODE}_energy_potential) \
+	  --potential-file $TMPLDIR/resources/energy_potential \
 	  --limit-results 10 \
 	| column -t \
 	> "$OUTFILE_CUTTING_SUGGESTIONS"
@@ -677,7 +725,7 @@ cat $TMPLDIR/foundation/atom_energies \
 | voronota score-contacts-quality \
   --default-mean -0.34 \
   --default-sd 0.19 \
-  --means-and-sds-file <(voronota-resources ${ENERGY_MODE}_energy_means_and_sds) \
+  --means-and-sds-file $TMPLDIR/resources/energy_means_and_sds \
   --external-weights-file $TMPLDIR/foundation/depth_values \
   --smoothing-window $SMOOTHING_WINDOW \
   --atom-scores-file $TMPLDIR/atom_quality_scores \
@@ -821,7 +869,7 @@ cat $TMPLDIR/foundation/atom_energies \
 | voronota score-contacts-quality \
   --default-mean -0.34 \
   --default-sd 0.19 \
-  --means-and-sds-file <(voronota-resources ${ENERGY_MODE}_energy_means_and_sds) \
+  --means-and-sds-file $TMPLDIR/resources/energy_means_and_sds \
   --external-weights-file $TMPLDIR/foundation/depth_values \
   --smoothing-window "$(echo "0,$SMOOTHING_WINDOW" | sed 's|^0,\(.\+,.\+\).*|\1|')" \
   --residue-scores-file $TMPLDIR/residue_quality_scores_for_plot \
@@ -1048,7 +1096,7 @@ then
 	| awk '{print $1 " " $2 " " $5 " " $3}' \
 	| tr ';' '_' \
 	| voronota score-contacts-energy \
-	  --potential-file <(voronota-resources ${ENERGY_MODE}_energy_potential) \
+	  --potential-file $TMPLDIR/resources/energy_potential \
 	| awk '{print $5 " " $2 " " $3 " " $4 " " ($4/($2+$3))}' \
 	> $TMPLDIR/energy_descriptor_of_contacts_selection
 fi
@@ -1086,7 +1134,7 @@ then
 	| awk '{if($2=="c<solvent>") {print $1 " " $2 " " $5 " " $3} else {print $1 " " $2 " " $5 " 0"}}' \
 	| tr ';' '_' \
 	| voronota score-contacts-energy \
-	  --potential-file <(voronota-resources ${ENERGY_MODE}_energy_potential) \
+	  --potential-file $TMPLDIR/resources/energy_potential \
 	  --depth "$SURFACE_CRAVING_DEPTH_VALUE" \
 	  --atom-scores-file $TMPLDIR/surface_atom_energies \
 	> /dev/null
