Enhanced VoroMQA script CASP-related output features.

diff --git a/voronota-voromqa b/voronota-voromqa
--- a/voronota-voromqa
+++ b/voronota-voromqa
@@ -16,6 +16,7 @@ OUTFILE_MAP=""
 OUTFILE_SCREENSHOT=""
 OUTFILE_SCORES_FOR_CASP=""
 OUTFILE_SCORES_FOR_CASP_PDB=""
+OUTFILE_SCORES_FOR_CASP_LOG=""
 OUTDIR_SUMMARY_FOR_POTENTIAL=""
 SMOOTHING_WINDOW="5"
 ATOMS_QUERY_PARAMETERS=""
@@ -96,6 +97,10 @@ do
 		;;
 	--output-scores-for-CASP-pdb)
 		OUTFILE_SCORES_FOR_CASP_PDB="$OPTARG"
+		shift
+		;;
+	--output-scores-for-CASP-log)
+		OUTFILE_SCORES_FOR_CASP_LOG="$OPTARG"
 		shift
 		;;
 	--outdir-summary-for-potential)
@@ -232,6 +237,12 @@ fi
 if [ -z "$OUTFILE_SCORES_FOR_CASP" ] && [ -n "$OUTFILE_SCORES_FOR_CASP_PDB" ]
 then
 	echo >&2 "Error: '--output-scores-for-CASP-pdb' cannot be used without '--output-scores-for-CASP'"
+	exit 1
+fi
+
+if [ -z "$OUTFILE_SCORES_FOR_CASP" ] && [ -n "$OUTFILE_SCORES_FOR_CASP_LOG" ]
+then
+	echo >&2 "Error: '--output-scores-for-CASP-log' cannot be used without '--output-scores-for-CASP'"
 	exit 1
 fi
 
@@ -786,6 +797,16 @@ then
 	  --completeness-threshold 0.85 \
 	  --converted-local-scores "$TMPLDIR/residue_quality_scores_for_casp" \
 	> "$OUTFILE_SCORES_FOR_CASP"
+	
+	if [ -n "$OUTFILE_SCORES_FOR_CASP_LOG" ]
+	then
+		mkdir -p $(dirname "$OUTFILE_SCORES_FOR_CASP_LOG")
+		paste \
+		  "$TMPLDIR/residue_quality_scores" \
+		  "$TMPLDIR/residue_quality_scores_for_casp" \
+		| column -t \
+		> "$OUTFILE_SCORES_FOR_CASP_LOG"
+	fi
 	
 	if [ -n "$OUTFILE_SCORES_FOR_CASP_PDB" ]
 	then
