Updated logging in script.

diff --git a/expansion_js/voronota-js-pdb-utensil-gather-ensemble b/expansion_js/voronota-js-pdb-utensil-gather-ensemble
--- a/expansion_js/voronota-js-pdb-utensil-gather-ensemble
+++ b/expansion_js/voronota-js-pdb-utensil-gather-ensemble
@@ -618,10 +618,10 @@ NDOMAINS=10
 for i in 1 2
 do
 	MT ../structures_reduced_superposed_multimodel_named.cif ../structure_reduced_msa.fasta -s 0 --tree 1 --nDomains "$NDOMAINS" \
-	> "./split.log" \
-	2> "./split.err"
+	> "./split_${i}.log" \
+	2> "./split_${i}.err"
 	
-	cat "./split.log" \
+	cat "./split_${i}.log" \
 	| egrep '^Rigid Block ' \
 	| sed 's/^Rigid\sBlock\s\(\S\+\)\s*\:\s*\(\S.\+\)Loss\s\(\S\+\)\s.*$/\2 \3/' \
 	| sed 's/\.\.\+//' \
@@ -634,7 +634,7 @@ do
 	
 	if [ ! -s "./mt_domains.txt" ]
 	then
-		echo >&2 "Error: MT did not produce domain splits in step ${i}, see $(pwd)/split.err"
+		echo >&2 "Error: MT did not produce domain splits in step ${i}, see $(pwd)/split_${i}.err"
 		exit 0
 	fi
 	
@@ -750,7 +750,7 @@ cat "./mt/mt_domains.txt" | column -t
 echo
 echo "MT warnings summary:"
 {
-echo "$(cat ./mt/split.err | egrep . | wc -l) - lines_in_split.err"
+echo "$(cat ./mt/split_1.err ./mt/split_2.err | egrep . | wc -l) - lines_in_split.err"
 echo "$(cat ./mt/morph.err | egrep . | wc -l) - lines_in_morph.err"
 } | column -t | tr '_' ' '
 
@@ -762,7 +762,7 @@ echo "$(basename ${REDUCED_OUTPUTDIR})/mt/marked_structures/         -  director
 echo "$(basename ${REDUCED_OUTPUTDIR})/mt/morphs/                    -  directory with structured of morph states"
 
 echo
-echo "Commands to view raw structures:"
+echo "Commands to view marked structures:"
 echo "pymol ${REDUCED_OUTPUTDIR}/mt/marked_structures/*"
 echo "voronota-gl ${REDUCED_OUTPUTDIR}/mt/marked_structures/*"
 
