Improced iface data graps v2 scripts.

diff --git a/expansion_js/voronota-js-fast-iface-data-graph-v2-stats b/expansion_js/voronota-js-fast-iface-data-graph-v2-stats
--- a/expansion_js/voronota-js-fast-iface-data-graph-v2-stats
+++ b/expansion_js/voronota-js-fast-iface-data-graph-v2-stats
@@ -22,11 +22,11 @@ Standard output:
 Examples:
 
     find ./input_complexes/ -type f -name '*.pdb' \
-    | voronota-js-fast-iface-data-graph-v2 --config ./config/akbps.txt --input _list --processors 8 --output-data-prefix ./data_graphs_raw/ \
+    | voronota-js-fast-iface-data-graph-v2 --config ./config/akbps --input _list --processors 8 --output-data-prefix ./data_graphs_raw/ \
     | voronota-js-fast-iface-data-graph-v2-stats --calculate-columns-statistics ./data_graph_statistics_
 
     find ./input_complexes/ -type f -name '*.pdb' \
-    | voronota-js-fast-iface-data-graph-v2 --config ./config/akbps.txt --input _list --processors 8 --output-data-prefix ./data_graphs_raw/ \
+    | voronota-js-fast-iface-data-graph-v2 --config ./config/akbps --input _list --processors 8 --output-data-prefix ./data_graphs_raw/ \
     | voronota-js-fast-iface-data-graph-v2-stats --standardize-columns-using-statistics ./data_graph_statistics_ --output-data-prefix ./data_graphs_standardized/
     
     voronota-js-fast-iface-data-graph-v2-stats --input-prefix ./data_graphs_raw/model1.pdb_ --standardize-columns-using-statistics ./data_graph_statistics_ --output-data-prefix ./data_graphs_standardized/
@@ -130,15 +130,15 @@ fi
 
 while read -r INPREFIX
 do
-	if [ ! -s "${INPREFIX}nodes.txt" ]
+	if [ ! -s "${INPREFIX}nodes" ]
 	then
-		echo >&2 "Error: input graph nodes file '${INPREFIX}nodes.txt' does not exist"
+		echo >&2 "Error: input graph nodes file '${INPREFIX}nodes' does not exist"
 		exit 1
 	fi
 	
-	if [ ! -s "${INPREFIX}links.txt" ]
+	if [ ! -s "${INPREFIX}links" ]
 	then
-		echo >&2 "Error: input graph links file '${INPREFIX}links.txt' does not exist"
+		echo >&2 "Error: input graph links file '${INPREFIX}links' does not exist"
 		exit 1
 	fi
 done \
@@ -149,18 +149,18 @@ done \
 if [ -n "$OUTSTATSFILEPREFIX" ]
 then
 
-cat "$TMPLDIR/input_list" | sed 's|$|nodes.txt|' | xargs -L 100 cat \
+cat "$TMPLDIR/input_list" | sed 's|$|nodes|' | xargs -L 100 cat \
 | awk '{if(NR==1 || $1!="ID1"){print $0}}' \
-> $TMPLDIR/nodes.txt
+> $TMPLDIR/nodes
 
-cat "$TMPLDIR/input_list" | sed 's|$|links.txt|' | xargs -L 100 cat \
+cat "$TMPLDIR/input_list" | sed 's|$|links|' | xargs -L 100 cat \
 | awk '{if(NR==1 || $1!="ir_contact_index1"){print $0}}' \
-> $TMPLDIR/links.txt
+> $TMPLDIR/links
 
 cd "$TMPLDIR"
 
 R --vanilla << 'EOF' > /dev/null
-for(obj in c("nodes.txt", "links.txt"))
+for(obj in c("nodes", "links"))
 {
 	dt=read.table(obj, header=TRUE, stringsAsFactors=FALSE);
 	valcolnames=setdiff(colnames(dt), c("ID1", "ID2", "contact_index", "ir_contact_index", "ir_contact_index1", "ir_contact_index2"));
@@ -181,7 +181,7 @@ for(obj in c("nodes.txt", "links.txt"))
 EOF
 
 R --vanilla << 'EOF' > /dev/null
-dt=read.table("nodes.txt", header=TRUE, stringsAsFactors=FALSE);
+dt=read.table("nodes", header=TRUE, stringsAsFactors=FALSE);
 valcolnames=setdiff(colnames(dt), c("ID1", "ID2", "contact_index", "ir_contact_index", "distance", "IRCAD_sum", "IRCAD_goodness"));
 dt=dt[,valcolnames];
 dt=scale(dt);
@@ -191,7 +191,7 @@ pca_rotation_matrix=pca_result$rotation[,1:NComp];
 pca_rotation_dt=as.data.frame(pca_rotation_matrix);
 pca_rotation_dt$name=rownames(pca_rotation_dt);
 pca_rotation_dt=pca_rotation_dt[,c("name", setdiff(colnames(pca_rotation_dt), "name"))];
-stats=read.table("stats_of_nodes.txt", header=TRUE, stringsAsFactors=FALSE);
+stats=read.table("stats_of_nodes", header=TRUE, stringsAsFactors=FALSE);
 stats$orig_order=1:nrow(stats);
 summary=merge(stats, pca_rotation_dt, all.x=TRUE);
 summary=summary[order(summary$orig_order), setdiff(colnames(summary), "orig_order")];
@@ -199,15 +199,15 @@ for(pccolname in paste0("PC", 1:NComp))
 {
 	summary[is.na(summary[,pccolname]), pccolname]=0;
 }
-write.table(summary, file="stats_of_nodes.txt", quote=FALSE, row.names=FALSE, col.names=TRUE, sep=" ");
+write.table(summary, file="stats_of_nodes", quote=FALSE, row.names=FALSE, col.names=TRUE, sep=" ");
 EOF
 
 cd - &> /dev/null
 
 mkdir -p "$(dirname ${OUTSTATSFILEPREFIX}file)"
 
-cat "${TMPLDIR}/stats_of_nodes.txt" | column -t > "${OUTSTATSFILEPREFIX}nodes.txt"
-cat "${TMPLDIR}/stats_of_links.txt" | column -t > "${OUTSTATSFILEPREFIX}links.txt"
+cat "${TMPLDIR}/stats_of_nodes" | column -t > "${OUTSTATSFILEPREFIX}nodes"
+cat "${TMPLDIR}/stats_of_links" | column -t > "${OUTSTATSFILEPREFIX}links"
 
 fi
 
@@ -216,15 +216,15 @@ fi
 if [ -n "$INSTATSFILEPREFIX" ]
 then
 
-if [ ! -s "${INSTATSFILEPREFIX}nodes.txt" ]
+if [ ! -s "${INSTATSFILEPREFIX}nodes" ]
 then
-	echo >&2 "Error: input file '${INSTATSFILEPREFIX}nodes.txt' does not exist"
+	echo >&2 "Error: input file '${INSTATSFILEPREFIX}nodes' does not exist"
 	exit 1
 fi
 
-if [ ! -s "${INSTATSFILEPREFIX}links.txt" ]
+if [ ! -s "${INSTATSFILEPREFIX}links" ]
 then
-	echo >&2 "Error: input file '${INSTATSFILEPREFIX}links.txt' does not exist"
+	echo >&2 "Error: input file '${INSTATSFILEPREFIX}links' does not exist"
 	exit 1
 fi
 
@@ -233,12 +233,12 @@ mkdir -p "$(dirname ${OUTPREFIX}file)"
 cat "$TMPLDIR/input_list" \
 | while read -r INPREFIX
 do
-	for OBJNAME in nodes.txt links.txt
+	for OBJNAME in nodes links
 do
 	STATSFILE="${INSTATSFILEPREFIX}${OBJNAME}"
 	INFILE="${INPREFIX}${OBJNAME}"
 	INFILEBASENAME="$(basename $INFILE)"
-	OUTFILE="${OUTPREFIX}${INFILEBASENAME}"
+	OUTFILE="${OUTPREFIX}${INFILEBASENAME}.csv"
 
 R --vanilla --args "$STATSFILE" "$INFILE" "$OUTFILE" << 'EOF' > /dev/null
 args=commandArgs(TRUE);
@@ -265,7 +265,7 @@ if(is.element("PC1", colnames(stats)))
 	dt_pcs=as.data.frame(dt_pcs);
 	dt=cbind(dt, dt_pcs);
 }
-write.table(dt, file=outfile, quote=FALSE, row.names=FALSE, col.names=TRUE, sep=" ");
+write.table(dt, file=outfile, quote=FALSE, row.names=FALSE, col.names=TRUE, sep=",");
 EOF
 
 	done
