Improved data graph script.

diff --git a/expansion_js/voronota-js-fast-iface-data-graph-v2 b/expansion_js/voronota-js-fast-iface-data-graph-v2
--- a/expansion_js/voronota-js-fast-iface-data-graph-v2
+++ b/expansion_js/voronota-js-fast-iface-data-graph-v2
@@ -7,7 +7,7 @@ cat >&2 << 'EOF'
 'voronota-js-fast-iface-data-graph-v2' script generates interface data graphs of protein complexes.
 
 Options:
-    --config                  string  *  input directory path for configuration files
+    --config-akbps            string  *  input file path for AKBPs configuration
     --input                   string  *  input file path or '_list' to read file paths from stdin
     --restrict-input          string     query to restrict input atoms, default is '[]'
     --subselect-contacts      string     query to subselect inter-chain contacts, default is '[]'
@@ -18,18 +18,18 @@ Options:
     --sbatch-parameters       string     sbatch parameters to run in parallel, default is ''
     --stdin-file              string     input file path to replace stdin
     --run-faspr               string     path to FASPR binary to rebuild side-chains
-    --input-is-script                    flag to treat input file as vs script
-    --as-assembly                        flag to treat input file as biological assembly
+    --input-is-script         string     flag to treat input file as vs script, default is 'false'
+    --as-assembly             string     flag to treat input file as biological assembly, default is 'false'
     --help | -h                          flag to display help message and exit
 
 Standard output:
-    space-separated table of generated file paths
+    list of generated output file path prefixes
     
 Examples:
 
-    voronota-js-fast-iface-data-graph-v2 --config ./config1 --input model.pdb --output-data-prefix ./data_graphs/
+    voronota-js-fast-iface-data-graph-v2 --config-akbps ./config/akbps.txt --input model.pdb --output-data-prefix ./data_graphs/
     
-    ls *.pdb | voronota-js-fast-iface-data-graph-v2 --config ./config1 --input _list --processors 8 --output-data-prefix ./data_graphs/
+    ls *.pdb | voronota-js-fast-iface-data-graph-v2 --config ./config/akbps.txt --input _list --processors 8 --output-data-prefix ./data_graphs/
 
 EOF
 exit 1
@@ -89,7 +89,7 @@ export LC_ALL=C
 
 command -v voronota-js &> /dev/null || { echo >&2 "Error: 'voronota-js' executable not in binaries path"; exit 1; }
 
-INCONFIGDIR=""
+INCONFIGAKBPS=""
 INFILE=""
 RESTRICT_INPUT="[]"
 SUBSELECT_CONTACTS="[]"
@@ -110,8 +110,8 @@ do
 	OPTARG="$2"
 	shift
 	case $OPTION in
-	--config)
-		INCONFIGDIR="$OPTARG"
+	--config-akbps)
+		INCONFIGAKBPS="$OPTARG"
 		shift
 		;;
 	--input)
@@ -155,10 +155,12 @@ do
 		shift
 		;;
 	--input-is-script)
-		INPUT_IS_SCRIPT="true"
+		INPUT_IS_SCRIPT="$OPTARG"
+		shift
 		;;
 	--as-assembly)
-		AS_ASSEMBLY="true"
+		AS_ASSEMBLY="$OPTARG"
+		shift
 		;;
 	-h|--help)
 		HELP_MODE="true"
@@ -175,9 +177,9 @@ then
 	print_help_and_exit
 fi
 
-if [ -z "$INCONFIGDIR" ]
+if [ -z "$INCONFIGAKBPS" ]
 then
-	echo >&2 "Error: configuration directory not provided"
+	echo >&2 "Error: input AKBPs configuration file not provided"
 	exit 1
 fi
 
@@ -193,15 +195,9 @@ then
 	exit 1
 fi
 
-if [ ! -d "$INCONFIGDIR" ]
+if [ ! -s "$INCONFIGAKBPS" ]
 then
-	echo >&2 "Error: configuration directory does not exist"
-	exit 1
-fi
-
-if [ ! -s "${INCONFIGDIR}/akbps" ]
-then
-	echo >&2 "Error: configuration directory does contain required file 'akbps'"
+	echo >&2 "Error: input AKBPs configuration file '$INCONFIGAKBPS' does not exist"
 	exit 1
 fi
 
@@ -346,7 +342,6 @@ then
 	find "$TMPLDIR/children_tables" -type f -not -empty \
 	| sort \
 	| xargs -L 1 cat \
-	| awk '{if(NR==1 || $1!="input_name") print $0}' \
 	> "$TMPLDIR/full_output_table"
 	
 	if [ -n "$OUTPUT_TABLE_FILE" ] && [ "$OUTPUT_TABLE_FILE" != "_stdout" ]
@@ -366,7 +361,7 @@ OUTPUT_TABLE_FILE="$(substitute_id_in_filename "$INFILE_BASENAME" "$OUTPUT_TABLE
 {
 cat << EOF
 var common_params={}
-common_params.akbps_lib='$INCONFIGDIR/akbps';
+common_params.akbps_lib='$INCONFIGAKBPS';
 common_params.input_is_script='$INPUT_IS_SCRIPT';
 common_params.input_as_assembly='$AS_ASSEMBLY';
 common_params.restrict_input_atoms='$RESTRICT_INPUT';
@@ -556,38 +551,14 @@ generate_model_data_graph_files=function(input_name)
 	var summary={}
 	
 	summary.input_name=input_name;
-	summary.output_nodes_file=common_params.output_prefix+""+input_name+"_nodes.txt";
-	summary.output_links_file=common_params.output_prefix+""+input_name+"_links.txt";
+	summary.output_files_prefix=common_params.output_prefix+""+input_name+"_";
+	summary.output_nodes_file=summary.output_files_prefix+"nodes.txt";
+	summary.output_links_file=summary.output_files_prefix+"links.txt";
 	
 	voronota_export_adjuncts_of_contacts("-inter-residue", "true", "-file", summary.output_nodes_file, "-contacts-use", "[inter_chain_contacts]", "-no-serial", "-adjuncts", adjuncts_to_output, "-adjacency-file", summary.output_links_file, "-saturate-adjacency");
 	voronota_assert_full_success("Failed to export contacts data");
 	
-	var summary_table={}
-	summary_table.header="";
-	summary_table.row="";
-	
-	Object.keys(summary).forEach(function(key)
-	{
-			summary_table.header+=key+" ";
-	});
-	
-	Object.keys(summary).forEach(function(key)
-	{
-		value=summary[key];
-		if(typeof value === 'number')
-		{
-			summary_table.row+=parseFloat(value.toFixed(5))+" ";
-		}
-		else
-		{
-			summary_table.row+=value+" ";
-		}
-	});
-	
-	summary_table.header=summary_table.header.trim();
-	summary_table.row=summary_table.row.trim();
-	
-	return summary_table;
+	return summary;
 }
 
 if(input_info_array.length<1)
@@ -656,14 +627,9 @@ for(var i=0;i<input_info_array.length;i++)
 	{
 		prepare_object(subinput.input_file, "model", common_params.run_faspr);
 		
-		var summary_table=generate_model_data_graph_files(subinput.input_file_name);
+		var summary=generate_model_data_graph_files(subinput.input_file_name);
 		
-		if(full_summary_table=="")
-		{
-			full_summary_table+=summary_table.header+"\n";
-		}
-		
-		full_summary_table+=summary_table.row+"\n";
+		full_summary_table+=summary.output_files_prefix+"\n";
 	}
 	catch(error)
 	{
