Corrected GNN package files existance check.

diff --git a/expansion_js/voronota-js-voroif-gnn b/expansion_js/voronota-js-voroif-gnn
--- a/expansion_js/voronota-js-voroif-gnn
+++ b/expansion_js/voronota-js-voroif-gnn
@@ -406,9 +406,9 @@ then
 	GNN_PACKAGE_FILES="${SCRIPTDIR}/voroif/gnn_packages/v1"
 fi
 
-if [ -z "$GNN_PACKAGE_FILES" ] || [ ! -d "$GNN_PACKAGE_FILES" ] || [ ! -s "$GNN_PACKAGE_FILES" ]
+if [ ! -e "$GNN_PACKAGE_FILES" ]
 then
-	echo >&2 "Error: no GNN package file or directory specified"
+	echo >&2 "Error: GNN package file or directory '${GNN_PACKAGE_FILES}' does not exist"
 	exit 1
 fi
 
