Added structures downloads caching in ensemble gathering script.

diff --git a/expansion_js/voronota-js-pdb-utensil-gather-ensemble b/expansion_js/voronota-js-pdb-utensil-gather-ensemble
--- a/expansion_js/voronota-js-pdb-utensil-gather-ensemble
+++ b/expansion_js/voronota-js-pdb-utensil-gather-ensemble
@@ -315,15 +315,39 @@ done \
 mkdir -p "./struct_to_seq_alignments"
 mkdir -p "./structures"
 
-echo >&2 "...... Fetching structure files from PDB, renumbering the entity chains by sequences, saving structures"
+echo >&2 "...... Downloading full structure files from PDB"
 
 cat "./pdbid_chain_sequence_table.tsv" \
 | while read -r PDBID CHAINID MSASEQ
 do
+	PDBIDSUBGROUP="$(echo ${PDBID} | sed 's/^\(..\).*$/\1/')"
+	PDBCACHEDFILE="${CACHEDIR}/structures/${PDBIDSUBGROUP}/${PDBID}.cif.gz"
+	if [ ! -s "${CACHEDIR}/structures/${PDBIDSUBGROUP}/${PDBID}.cif.gz" ]
+	then
+		mkdir -p "${CACHEDIR}/structures/${PDBIDSUBGROUP}"
+		cd "${CACHEDIR}/structures/${PDBIDSUBGROUP}"
+		wget -O "${PDBID}.cif.gz.tmp" -q "https://files.rcsb.org/download/${PDBID}.cif.gz"
+		mv "${PDBID}.cif.gz.tmp" "${PDBID}.cif.gz"
+		if [ ! -s "${PDBID}.cif.gz" ]
+		then
+			echo >&2 "Error: could not download mmCIF file for PDB ID '${PDBID}'"
+			exit 1
+		fi
+		cd - &> /dev/null
+	fi
+done
+
+echo >&2 "...... Importing structure files, renumbering the entity chains by sequences, saving structures"
+
+cat "./pdbid_chain_sequence_table.tsv" \
+| while read -r PDBID CHAINID MSASEQ
+do
+PDBIDSUBGROUP="$(echo ${PDBID} | sed 's/^\(..\).*$/\1/')"
+PDBCACHEDFILE="${CACHEDIR}/structures/${PDBIDSUBGROUP}/${PDBID}.cif.gz"
 {
 cat << EOF
 var params={}
-params.pdb_id='$PDBID';
+params.pdb_file='$PDBCACHEDFILE';
 params.chain_id='$CHAINID';
 params.sequence_str='$MSASEQ';
 params.strict='true';
@@ -333,7 +357,7 @@ cat << 'EOF'
 voronota_setup_defaults("-no-load-voromqa-potentials", "-no-load-more-atom-types", "-no-load-mock-voromqa-potential -include-heteroatoms");
 voronota_assert_full_success("Failed to setup defaults");
 
-voronota_fetch_mmcif("-pdb-id", params.pdb_id, "-assembly", 0, "-all-states", "-use-label-ids");
+voronota_import_mmcif("-files", [params.pdb_file], "-use-label-ids");
 voronota_assert_full_success("Failed to fetch structure");
 
 voronota_restrict_atoms("-use", "[-protein]");
