Added shuffle chains option for testing remapping in fast cad-score.

diff --git a/expansion_js/voronota-js-fast-iface-cadscore b/expansion_js/voronota-js-fast-iface-cadscore
--- a/expansion_js/voronota-js-fast-iface-cadscore
+++ b/expansion_js/voronota-js-fast-iface-cadscore
@@ -74,6 +74,7 @@ MAX_PROCESSORS="1"
 SBATCH_PARAMETERS=""
 STDIN_FILE="_stream"
 RUN_FASPR=""
+SHUFFLE_CHAINS=""
 TARGET_INPUT_IS_SCRIPT="false"
 MODEL_INPUT_IS_SCRIPT="false"
 AS_ASSEMBLY="false"
@@ -124,6 +125,10 @@ do
 		RUN_FASPR="$OPTARG"
 		shift
 		;;
+	--shuffle-chains)
+		SHUFFLE_CHAINS="$OPTARG"
+		shift
+		;;
 	--target-input-is-script)
 		TARGET_INPUT_IS_SCRIPT="true"
 		;;
@@ -171,7 +176,7 @@ fi
 
 if [ -n "$RUN_FASPR" ] && [ ! -s "$RUN_FASPR" ]
 then
-	echo >&2 "Error: FASPR binary executable file '$RUN_FASPR' does not exist"
+	echo >&2 "Error: FASPR binary file '$RUN_FASPR' does not exist"
 	exit 1
 fi
 
@@ -362,6 +367,7 @@ common_params.restrict_input_atoms='$RESTRICT_INPUT';
 common_params.test_common_ids='$TEST_COMMON_IDS';
 common_params.contacts_subselection='$SUBSELECT_CONTACTS';
 common_params.run_faspr='$RUN_FASPR';
+common_params.shuffle_chains='$SHUFFLE_CHAINS';
 common_params.remap_chains='$REMAP_CHAINS';
 common_params.crude_mode='$CRUDE_MODE'
 common_params.output_table_file='$OUTPUT_TABLE_FILE';
@@ -384,7 +390,7 @@ EOF
 done
 
 cat << 'EOF'
-prepare_atoms=function(params, run_faspr)
+prepare_atoms=function(params, run_faspr, shuffle_chains)
 {
 	voronota_restrict_atoms("-use", params.restrict_input_atoms);
 	voronota_assert_full_success("Failed to restrict input atoms by the input query");
@@ -393,6 +399,16 @@ prepare_atoms=function(params, run_faspr)
 	{
 		voronota_faspr("-lib-file", run_faspr);
 		voronota_assert_full_success("Failed to run FASPR");
+	}
+	
+	if(shuffle_chains!="")
+	{
+		voronota_setup_random_seed("-seed", shuffle_chains);
+		voronota_assert_full_success("Failed to set random seed");
+		voronota_set_chain_name("_shuffle");
+		voronota_assert_full_success("Failed to shuffle chains");
+		voronota_order_atoms_by_residue_id();
+		voronota_assert_full_success("Failed reorder atoms by residue ids after shuffling chains");
 	}
 	
 	if(params.crude_mode=="true")
@@ -564,7 +580,7 @@ target_object=voronota_last_output().results[0].output.objects[0].name;
 
 voronota_pick_objects("-names", target_object);
 
-var target_initial_number_of_accepted_atoms=prepare_atoms(common_params, "");
+var target_initial_number_of_accepted_atoms=prepare_atoms(common_params, "", "");
 
 if(common_params.test_common_ids=="true")
 {
@@ -614,7 +630,7 @@ for(var i=0;i<input_info_array.length;i++)
 		
 		voronota_pick_objects("-names", model_object);
 		
-		var model_initial_number_of_accepted_atoms=prepare_atoms(common_params, common_params.run_faspr);
+		var model_initial_number_of_accepted_atoms=prepare_atoms(common_params, common_params.run_faspr, common_params.shuffle_chains);
 		
 		if(common_params.test_common_ids=="true")
 		{
