Improved convenience scripts for relaxing and fast scoring.

diff --git a/expansion_js/voronota-js-focused-relax-with-openmm b/expansion_js/voronota-js-focused-relax-with-openmm
--- a/expansion_js/voronota-js-focused-relax-with-openmm
+++ b/expansion_js/voronota-js-focused-relax-with-openmm
@@ -13,10 +13,13 @@ Options:
     --conda-path              string     conda installation path, default is ''
     --conda-env               string     conda environment name, default is ''
     --forcefield              string     forcefield name, default is 'amber99sb', some others are: 'amber14-all', 'charmm36'
-    --water-forcefield        string     water forcefiled name, default is '', some others are: 'amber99_obc', 'amber14/tip3pfb', 'charmm36/water'
+    --water-forcefield        string     water forcefiled name, default is 'amber99_obc', some others are: '', 'amber14/tip3pfb', 'charmm36/water'
     --max-iterations          number     max number of iterations, default is 100
-    --score-at-end            string     mode for scoring interface at the end, default is ''. others are: 'fast_iface', 'full_iface', 'full'
+    --score-at-end            string     mode for scoring interface at the end, default is '', others are: 'fast_iface', 'full_iface', 'full'
+    --scoring-params          string     additional parameters for scoring, default is ''
     --multiple-tries          number     number of tries to generate and score interfaces, default is ''
+    --force-cuda                         flag to force the platform to be CUDA
+    --trim-output                        flag to restrict output to only heavy atoms of proteins and nucleic acids
     --no-preparation                     flag to not run PDBFixer and to not add hydrogens
     --no-simulation                      flag to not run any simulations
     --print-time                         flag to print time in seconds
@@ -28,6 +31,10 @@ Standard output:
 Examples:
 
     voronota-js-focused-relax-with-openmm --input model.pdb --output relaxed_model.pdb
+    
+    voronota-js-focused-relax-with-openmm --conda-path ~/anaconda3 --conda-env alphafold2 \
+      --forcefield amber14-all --water-forcefield amber14/tip3pfb \
+      -i model.pdb -o relaxed_model.pdb --score-at-end fast_iface --trim-output
 
 EOF
 exit 1
@@ -37,6 +44,7 @@ SECONDS=0
 SECONDS_PREPARE=0
 SECONDS_SIMULATE=0
 SECONDS_SCORE=0
+SECONDS_OUTPUT=0
 
 readonly ZEROARG=$0
 
@@ -58,10 +66,13 @@ FOCUS_MODE="whole_structure"
 CONDA_PATH=""
 CONDA_ENV=""
 FORCEFIELD="amber99sb"
-WATER_FORCEFIELD=""
+WATER_FORCEFIELD="amber99_obc"
 MAX_ITERATIONS="100"
 SCORE_AT_END=""
+SCORING_PARAMS=""
 MULTIPLE_TRIES=""
+FORCE_CUDA="false"
+TRIM_OUTPUT="false"
 NO_PREPARATION="false"
 NO_SIMULATION="false"
 PRINT_TIME="false"
@@ -109,9 +120,19 @@ do
 		SCORE_AT_END="$OPTARG"
 		shift
 		;;
+	--scoring-params)
+		SCORING_PARAMS="$OPTARG"
+		shift
+		;;
 	--multiple-tries)
 		MULTIPLE_TRIES="$OPTARG"
 		shift
+		;;
+	--force-cuda)
+		FORCE_CUDA="true"
+		;;
+	--trim-output)
+		TRIM_OUTPUT="true"
 		;;
 	--no-preparation)
 		NO_PREPARATION="true"
@@ -167,7 +188,7 @@ then
 	exit 1
 fi
 
-if [ "$FOCUS_MODE" != "whole_structure" ]
+if [ "$FOCUS_MODE" != "whole_structure" ] || [ "$TRIM_OUTPUT" == "true" ]
 then
 	command -v voronota-js &> /dev/null || { echo >&2 "Error: 'voronota-js' executable not in binaries path"; exit 1; }
 fi
@@ -250,15 +271,6 @@ fixer.findMissingAtoms()
 fixer.addMissingAtoms(seed=999)
 EOF
 
-if [ -n "$WATER_FORCEFIELD" ] && [[ $WATER_FORCEFIELD != *"_obc"* ]]
-then
-cat << 'EOF'
-maxSize = max(max((pos[i] for pos in fixer.positions))-min((pos[i] for pos in fixer.positions)) for i in range(3))
-boxSize = maxSize*Vec3(1, 1, 1)
-fixer.addSolvent(boxSize)
-EOF
-fi
-
 if [ -n "$WATER_FORCEFIELD" ]
 then
 cat << 'EOF'
@@ -274,6 +286,16 @@ cat << 'EOF'
 modeller = Modeller(fixer.topology, fixer.positions)
 random.seed(999);
 modeller.addHydrogens(forcefield)
+EOF
+
+if [ -n "$WATER_FORCEFIELD" ] && [[ $WATER_FORCEFIELD != *"_obc"* ]]
+then
+cat << 'EOF'
+modeller.addSolvent(forcefield, padding=0.2*nanometers)
+EOF
+fi
+
+cat << 'EOF'
 PDBFile.writeFile(modeller.topology, modeller.positions, open('prepared.pdb', 'w'), keepIds=True)
 EOF
 	} \
@@ -365,7 +387,21 @@ EOF
 
 cat << 'EOF'
 integrator = VerletIntegrator(0.001*picoseconds)
+EOF
+
+	if [ "$FORCE_CUDA" == "true" ]
+	then
+cat << 'EOF'
+platform = Platform.getPlatformByName('CUDA')
+simulation = Simulation(pdb.topology, system, integrator, platform)
+EOF
+	else
+cat << 'EOF'
 simulation = Simulation(pdb.topology, system, integrator)
+EOF
+	fi
+
+cat << 'EOF'
 simulation.context.setPositions(pdb.positions)
 simulation.minimizeEnergy(maxIterations=MAX_ITERATIONS)
 positions = simulation.context.getState(getPositions=True).getPositions()
@@ -418,38 +454,61 @@ if [ "$SCORE_AT_END" == "fast_iface" ]
 then
 	if [ -n "$MULTIPLE_TRIES" ]
 	then
-		cat list_to_score.txt | voronota-js-fast-iface-voromqa -i _list | tee scores.txt | column -t
+		cat list_to_score.txt | voronota-js-fast-iface-voromqa -i _list $SCORING_PARAMS | tee scores.txt | column -t
 		cp "$(cat scores.txt | awk '{print $1}' | egrep '^relaxed' | head -1)" "relaxed.pdb"
 	else
-		cat list_to_score.txt | voronota-js-fast-iface-voromqa -i _list | column -t
+		cat list_to_score.txt | voronota-js-fast-iface-voromqa -i _list $SCORING_PARAMS | column -t
 	fi
 fi
 
 if [ "$SCORE_AT_END" == "full_iface" ]
 then
-	cat list_to_score.txt | voronota-js-voromqa -i _list --inter-chain --processors 2 | column -t
+	cat list_to_score.txt | voronota-js-voromqa -i _list --inter-chain --processors 2 $SCORING_PARAMS | column -t
 fi
 
 if [ "$SCORE_AT_END" == "full" ]
 then
-	cat list_to_score.txt | voronota-js-voromqa -i _list --processors 2 | column -t
+	cat list_to_score.txt | voronota-js-voromqa -i _list --processors 2 $SCORING_PARAMS | column -t
 fi
 
 SECONDS_SCORE="$SECONDS"
 
-cd - &> /dev/null
-
-if [ "$OUTFILE" != "/dev/null" ]
+if [ "$TRIM_OUTPUT" == "true" ]
 then
-	mkdir -p "$(dirname "$OUTFILE")"
+	{
+cat << 'EOF'
+voronota_import("-file", "relaxed.pdb");
+voronota_assert_partial_success("Failed to import file");
+
+voronota_export_atoms("-file", "trimmed_relaxed.pdb", "-as-pdb");
+voronota_assert_full_success("Failed to export atoms");
+EOF
+	} \
+	| voronota-js --no-setup-defaults
+	
+	if [ ! -s "trimmed_relaxed.pdb" ]
+	then
+		echo >&2 "Error: failed trim output"
+		exit 1
+	fi
+
+	mv "trimmed_relaxed.pdb" "relaxed.pdb"
 fi
 
-cat "$TMPLDIR/relaxed.pdb" > "$OUTFILE"
+cd - &> /dev/null
+
+if [ -n "$OUTFILE" ] && [ "$OUTFILE" != "/dev/null" ]
+then
+	mkdir -p "$(dirname "$OUTFILE")"
+	mv "$TMPLDIR/relaxed.pdb" "$OUTFILE"
+fi
+
+SECONDS_OUTPUT="$SECONDS"
 
 if [ "$PRINT_TIME" == "true" ]
 then
-	echo "$SECONDS_PREPARE $SECONDS_SIMULATE $SECONDS_SCORE" \
-	| awk '{print "seconds:" $1 "+" ($2-$1) "+" ($3-$1) "=" $3}'
+	echo "$SECONDS_PREPARE $SECONDS_SIMULATE $SECONDS_SCORE $SECONDS_OUTPUT" \
+	| awk '{print "seconds:" $1 "+" ($2-$1) "+" ($3-$2) "+" ($4-$3) "=" $4}'
 fi
 
 exit 0
