Added custom radii file option in fast iface contacts script.

diff --git a/expansion_js/voronota-js-fast-iface-contacts b/expansion_js/voronota-js-fast-iface-contacts
--- a/expansion_js/voronota-js-fast-iface-contacts
+++ b/expansion_js/voronota-js-fast-iface-contacts
@@ -16,6 +16,7 @@ Options:
     --sbatch-parameters       string     sbatch parameters to run in parallel, default is ''
     --stdin-file              string     input file path to replace stdin
     --run-faspr               string     path to FASPR binary to rebuild side-chains
+    --custom-radii-file       string     path to file with van der Waals radii assignment rules
     --with-sas-areas                     flag to also compute and output solvent-accessible areas of interface residue atoms
     --coarse-grained                     flag to output a inter-residue contacts
     --input-is-script                    flag to treat input file as vs script
@@ -96,6 +97,7 @@ MAX_PROCESSORS="1"
 SBATCH_PARAMETERS=""
 STDIN_FILE="_stream"
 RUN_FASPR=""
+CUSTOM_RADII_FILE=""
 WITH_SAS_AREAS="false"
 COARSE_GRAINED="false"
 INPUT_IS_SCRIPT="false"
@@ -145,6 +147,10 @@ do
 		;;
 	--run-faspr)
 		RUN_FASPR="$OPTARG"
+		shift
+		;;
+	--custom-radii-file)
+		CUSTOM_RADII_FILE="$OPTARG"
 		shift
 		;;
 	--with-sas-areas)
@@ -203,6 +209,12 @@ fi
 if [ -n "$RUN_FASPR" ] && [ ! -s "$RUN_FASPR" ]
 then
 	echo >&2 "Error: FASPR binary executable file '$RUN_FASPR' does not exist"
+	exit 1
+fi
+
+if [ -n "$CUSTOM_RADII_FILE" ] && [ ! -s "$CUSTOM_RADII_FILE" ]
+then
+	echo >&2 "Error: custom file '$CUSTOM_RADII_FILE' does not exist"
 	exit 1
 fi
 
@@ -359,6 +371,7 @@ common_params.input_as_assembly='$AS_ASSEMBLY';
 common_params.restrict_input_atoms='$RESTRICT_INPUT';
 common_params.contacts_subselection='$SUBSELECT_CONTACTS';
 common_params.run_faspr='$RUN_FASPR';
+common_params.custom_radii_file='$CUSTOM_RADII_FILE';
 common_params.use_hbplus='$USE_HBPLUS';
 common_params.with_sas_areas='$WITH_SAS_AREAS';
 common_params.coarse_grained='$COARSE_GRAINED';
@@ -597,12 +610,17 @@ if(common_params.run_faspr===undefined)
 	common_params.run_faspr="";
 }
 
+if(common_params.custom_radii_file===undefined)
+{
+	common_params.custom_radii_file="";
+}
+
 if(common_params.output_contacts_file===undefined || common_params.output_contacts_file==="")
 {
 	common_params.output_contacts_file="_stdout";
 }
 
-voronota_setup_defaults("-no-load-voromqa-potentials -no-load-more-atom-types -no-load-mock-voromqa-potential -include-heteroatoms");
+voronota_setup_defaults("-no-load-voromqa-potentials", "-no-load-more-atom-types", "-no-load-mock-voromqa-potential", "-include-heteroatoms", "-radii-file", common_params.custom_radii_file);
 voronota_assert_full_success("Failed to setup defaults");
 
 for(var i=0;i<input_info_array.length;i++)
