Improved ensemble gathering script.

diff --git a/expansion_js/voronota-js-pdb-utensil-gather-ensemble b/expansion_js/voronota-js-pdb-utensil-gather-ensemble
--- a/expansion_js/voronota-js-pdb-utensil-gather-ensemble
+++ b/expansion_js/voronota-js-pdb-utensil-gather-ensemble
@@ -160,7 +160,7 @@ cd "$CACHEDIR"
 CACHEDIR="$(pwd)"
 cd - &> /dev/null
 
-CLUSTERSFILE="${CACHEDIR}/clusters-by-entity-${SEQIDENTITY}-$(date '+%Y-%m-%d').txt"
+CLUSTERSFILE="${CACHEDIR}/clusters-by-entity-${SEQIDENTITY}-year-$(date '+%Y-week-%V').txt"
 
 echo >&2 "... Preparing the sequence-based clustering info"
 
@@ -206,7 +206,7 @@ NUMOFENTITIES="$(cat ${TMPLDIR}/entities | wc -l)"
 
 LISTOFENTITIES="$(cat ${TMPLDIR}/entities | tr '\n' ',' | sed 's/,$//')"
 
-RAW_JOBID="$(cat ${TMPLDIR}/entities | head -1)__$(cat ${TMPLDIR}/entities | tail -1)__raw__$(echo ${LISTOFENTITIES} | sha256sum | awk '{print $1}')"
+RAW_JOBID="$(cat ${TMPLDIR}/entities | head -1)__$(cat ${TMPLDIR}/entities | tail -1)__raw__$(echo ${LISTOFENTITIES} | md5sum | awk '{print $1}')"
 
 RAW_OUTPUTDIR="${OUTPUTDIR}/${RAW_JOBID}"
 
@@ -350,7 +350,7 @@ cd "$RAW_OUTPUTDIR"
 
 RAW_OUTPUTDIR="$(pwd)"
 
-REDUCED_JOBID="$(echo ${RAW_JOBID} | sed 's|__raw__.*$|__reduced_|')_$(cat ./structure_sequence_table.tsv | awk -v maxloss=${SIZECONDITION} '{if($4<=maxloss){print $1}}' | sort | sha256sum | awk '{print $1}')"
+REDUCED_JOBID="$(echo ${RAW_JOBID} | sed 's|__raw__.*$|__reduced_|')_$(cat ./structure_sequence_table.tsv | awk -v maxloss=${SIZECONDITION} '{if($4<=maxloss){print $1}}' | sort | md5sum | awk '{print $1}')"
 
 cd ../
 
@@ -499,7 +499,7 @@ var representative_name=voronota_last_output().results[0].output.qcprot_results_
 voronota_qcprot_many("-target", representative_name, "-target-sel", "[]", "-model-sel", "[]", "-output-rmsd-file", "./rmsd_for_pairs_with_representive", "-verify-atom-ids");
 voronota_assert_full_success("Failed to compute optimal RMSD using qcprot for pairs with representive");
 
-voronota_export_atoms_to_mmcif("-file", "./structures_reduced_superposed/${objectname}");
+voronota_export_atoms_to_mmcif("-file", "./structures_reduced_superposed/${objectname}.cif");
 voronota_assert_full_success("Failed to output structures");
 
 voronota_export_atoms_to_mmcif_multimodel("-file", "./structures_reduced_superposed_multimodel_numbered.cif", "-model-numbers");
@@ -521,8 +521,12 @@ fi
 echo >&2 "... Summarizing output"
 
 echo
+echo "List of entities in the cluster: $(cat ${RAW_OUTPUTDIR}/entities | tr '\n' ' ')"
+
+echo
 echo "Stats:"
 {
+echo "$(cat ${RAW_OUTPUTDIR}/entities | wc -l) - number_of_entities"
 echo "$(cat ${RAW_OUTPUTDIR}/structure_sequence_table.tsv | wc -l) - number_of_raw_structures"
 echo "$(cat ${REDUCED_OUTPUTDIR}/structure_reduced_sequence_table.tsv | wc -l) - number_of_reduced_structures"
 if [ -f "${REDUCED_OUTPUTDIR}/rmsd_for_all_pairs" ]
@@ -563,8 +567,10 @@ fi
 
 echo
 
-if [ "$RUNMT" == "true" ]
+if [ "$RUNMT" != "true" ]
 then
+	exit 0
+fi
 
 if [ "$(cat ${REDUCED_OUTPUTDIR}/structure_reduced_sequence_table.tsv | wc -l)" -lt "2" ]
 then
@@ -579,12 +585,11 @@ echo >&2 "...... Checking if MT was already applied"
 if [ -f "${REDUCED_OUTPUTDIR}/mt/finished" ]
 then
 	echo >&2 "...... Skipping MT application"
-	exit 0
-fi
+else
 
 echo >&2 "...... Running MT"
 
-command -v MotionTree &> /dev/null || { echo >&2 "Error: 'MotionTree' executable not in binaries path"; exit 1; }
+command -v MT &> /dev/null || { echo >&2 "Error: 'MT' executable not in binaries path"; exit 1; }
 
 cd "${REDUCED_OUTPUTDIR}"
 
@@ -594,7 +599,11 @@ cd "./mt"
 NDOMAINS=10
 for i in 1 2
 do
-	MotionTree ../structures_reduced_superposed_multimodel_named.cif ../structure_reduced_msa.fasta -s 0 --tree 1 --nDomains "$NDOMAINS" \
+	MT ../structures_reduced_superposed_multimodel_named.cif ../structure_reduced_msa.fasta -s 0 --tree 1 --nDomains "$NDOMAINS" \
+	> "./split.log" \
+	2> "./split.err"
+	
+	cat "./split.log" \
 	| egrep '^Rigid Block ' \
 	| sed 's/^Rigid\sBlock\s\(\S\+\)\s*\:\s*\(\S.\+\)Loss\s\(\S\+\)\s.*$/\2 \3/' \
 	| sed 's/\.\.\+//' \
@@ -604,6 +613,12 @@ do
 	| sort -n -k2,2 -r \
 	| awk -v iteration="$i" '{if(iteration==2 || $2>0.0){print substr("ABCDEFGHIJKLMNOPQRSTUVWXYZ",NR,1) " " $1 " " $2}}' \
 	> "./mt_domains.txt"
+	
+	if [ ! -s "./mt_domains.txt" ]
+	then
+		echo >&2 "Error: MT did not produce domain splits in step ${i}, see $(pwd)/split.err"
+		exit 0
+	fi
 	
 	NDOMAINS="$(cat ./mt_domains.txt | wc -l)"
 	if [ "$NDOMAINS" -lt "2" ]
@@ -654,13 +669,15 @@ EOF
 } \
 | voronota-js --no-setup-defaults
 
-echo >&2 "...... Using MT output to generate morphs"
+echo >&2 "...... Using MT to generate morphs"
 
 mkdir -p "./mt/morphs"
 
 cd "./mt/morphs"
 
-MotionTree ../../structures_reduced_superposed_multimodel_named.cif ../../structure_reduced_msa.fasta -s 10 --tree 1 --nDomains "$NDOMAINS" -o ./morph > ../morphs.log
+MT ../../structures_reduced_superposed_multimodel_named.cif ../../structure_reduced_msa.fasta -s 10 --tree 1 --nDomains "$NDOMAINS" -o ./morph \
+> ../morph.log \
+2> ../morph.err
 
 rm ./tmp*
 
@@ -703,6 +720,28 @@ cd ..
 echo "yes" > "./finished"
 
 fi
+
+cd "${REDUCED_OUTPUTDIR}"
+
+echo
+echo "MT split summary:"
+cat "./mt/mt_domains.txt" | column -t
+
+echo
+echo "MT warnings summary:"
+{
+echo "$(cat ./mt/split.err | egrep . | wc -l) - lines_in_split.err"
+echo "$(cat ./mt/morph.err | egrep . | wc -l) - lines_in_morph.err"
+} | column -t | tr '_' ' '
+
+echo
+echo "MT output files:"
+echo "$(basename ${REDUCED_OUTPUTDIR})/mt/                           -  root data directory"
+echo "$(basename ${REDUCED_OUTPUTDIR})/mt/mt_domains.txt             -  split info"
+echo "$(basename ${REDUCED_OUTPUTDIR})/mt/marked_structured/         -  directory with structures with domains marked by different chain IDs"
+echo "$(basename ${REDUCED_OUTPUTDIR})/mt/morphs/                    -  directory with structured of morph states"
+
+echo
 
 exit 0
 
