Improved ligands cadscore script.

diff --git a/expansion_js/voronota-js-ligand-cadscore b/expansion_js/voronota-js-ligand-cadscore
--- a/expansion_js/voronota-js-ligand-cadscore
+++ b/expansion_js/voronota-js-ligand-cadscore
@@ -21,6 +21,7 @@ Input options, alternative:
     --casp15-model-pose           string  *  pose number to select from the model data file in CASP15 format
 
 Other options:
+    --details-dir                 string     directory to output lists of contacts used for scoring
     --help | -h                              flag to display help message and exit
     
 Standard output:
@@ -65,6 +66,7 @@ CASP15_TARGET=""
 CASP15_TARGET_POSE=""
 CASP15_MODEL=""
 CASP15_MODEL_POSE=""
+DETAILS_DIR=""
 HELP_MODE="false"
 
 while [[ $# > 0 ]]
@@ -111,6 +113,10 @@ do
 		;;
 	--casp15-model-pose)
 		CASP15_MODEL_POSE="$OPTARG"
+		shift
+		;;
+	--details-dir)
+		DETAILS_DIR="$OPTARG"
 		shift
 		;;
 	-h|--help)
@@ -216,7 +222,8 @@ EOF
 		
 	voronota-js-ligand-cadscore \
 	  --target-receptor "${TMPLDIR}/target_receptor.pdb" --target-ligands "$(cat ${TMPLDIR}/target_list)" --target-ligand-ids "$(cat ${TMPLDIR}/target_list_ids)" \
-      --model-receptor "${TMPLDIR}/model_receptor.pdb" --model-ligands "$(cat ${TMPLDIR}/model_list)" --model-ligand-ids "$(cat ${TMPLDIR}/model_list_ids)"
+      --model-receptor "${TMPLDIR}/model_receptor.pdb" --model-ligands "$(cat ${TMPLDIR}/model_list)" --model-ligand-ids "$(cat ${TMPLDIR}/model_list_ids)" \
+      --details-dir "$DETAILS_DIR"
 	
 	exit 0
 fi
@@ -242,7 +249,6 @@ do
 	fi
 done < <(echo "${TARGET_LIGANDS}" | tr ' ' '\n' | egrep .)
 
-
 while read LIGFILE
 do
 	if [ ! -s "$LIGFILE" ]
@@ -252,6 +258,16 @@ do
 	fi
 done < <(echo "${MODEL_LIGANDS}" | tr ' ' '\n' | egrep .)
 
+if [ -n "$DETAILS_DIR" ]
+then
+	mkdir -p "$DETAILS_DIR"
+	if [ ! -d "$DETAILS_DIR" ]
+	then
+		echo >&2 "Error: failed to access or create details output directory '$DETAILS_DIR'"
+		exit 1
+	fi
+fi
+
 {
 cat << EOF
 var params={}
@@ -259,6 +275,8 @@ params.target_receptor='$TARGET_RECEPTOR';
 params.target_ligands=[];
 params.model_receptor='$MODEL_RECEPTOR';
 params.model_ligands=[];
+params.details_dir='$DETAILS_DIR';
+params.details_dir=params.details_dir.trim();
 EOF
 
 paste <(echo ${TARGET_LIGANDS} | tr ' ' '\n' | egrep .) <(echo ${TARGET_LIGAND_IDS} | tr ' ' '\n' | egrep .) \
@@ -293,7 +311,7 @@ for(var i=0;i<params.target_ligands.length;i++)
 	voronota_import('-file', params.target_ligands[i].ligand_file, '-title', 'tlig'+i);
 	var object_name=voronota_last_output().results[0].output.object_name;
 	voronota_pick_objects(object_name);
-	voronota_set_chain_name('-chain-name', 'lig'+params.target_ligands[i].ligand_id);
+	voronota_set_chain_name('-chain-name', params.target_ligands[i].ligand_id);
 	voronota_set_tag_of_atoms('-tag', 'ligand');
 	voronota_unpick_objects();
 	target_object_names.push(object_name);
@@ -305,7 +323,7 @@ for(var i=0;i<params.model_ligands.length;i++)
 	voronota_import('-file', params.model_ligands[i].ligand_file, '-title', 'mlig'+i);
 	var object_name=voronota_last_output().results[0].output.object_name;
 	voronota_pick_objects(object_name);
-	voronota_set_chain_name('-chain-name', 'lig'+params.model_ligands[i].ligand_id);
+	voronota_set_chain_name('-chain-name', params.model_ligands[i].ligand_id);
 	voronota_set_tag_of_atoms('-tag', 'ligand');
 	voronota_unpick_objects();
 	model_object_names.push(object_name);
@@ -313,10 +331,10 @@ for(var i=0;i<params.model_ligands.length;i++)
 
 voronota_unpick_objects();
 
-voronota_merge_objects('-names', target_object_names, '-title', 'full_target');
-voronota_merge_objects('-names', model_object_names, '-title', 'full_model');
+voronota_merge_objects('-names', target_object_names, '-title', 'target_complex');
+voronota_merge_objects('-names', model_object_names, '-title', 'model_complex');
 
-voronota_pick_objects('-names', ['full_target', 'full_model']);
+voronota_pick_objects('-names', ['target_complex', 'model_complex']);
 voronota_delete_objects('-not-picked');
 voronota_set_atom_serials();
 
@@ -332,15 +350,19 @@ voronota_select_contacts('-use', '[-a1 [-t receptor] -a2 [-t ligand]]', '-name',
 voronota_select_atoms('-use', '[-sel-of-contacts iface]', '-full-residues', '-name', 'iface_atoms');
 voronota_select_contacts('-use', '[-a1 [iface_atoms] -a2 [iface_atoms] -min-seq-sep 1]', '-name', 'adjacent_to_iface');
 
-voronota_cad_score('-target', 'full_target', '-model', 'full_model', '-t-sel', '[iface]', '-also-site-based');
+voronota_cad_score('-target', 'target_complex', '-model', 'model_complex', '-t-sel', '[iface]', '-m-sel', '[iface]');
 iface_cadscore=voronota_last_output().results[0].output.residue_level_result;
-iface_cadscore_site_based=voronota_last_output().results[0].output.site_residue_level_result;
 
-voronota_cad_score('-target', 'full_target', '-model', 'full_model', '-t-sel', '[adjacent_to_iface]', '-also-site-based');
+voronota_cad_score('-target', 'target_complex', '-model', 'model_complex', '-t-sel', '[adjacent_to_iface]', '-m-sel', '[adjacent_to_iface]');
 adjacent_to_iface_cadscore=voronota_last_output().results[0].output.residue_level_result;
 
+if(params.details_dir.length>0)
+{
+	voronota_export_adjuncts_of_contacts('-inter-residue', '-adjuncts', 'area', '-contacts-use', '[iface]', '-file', params.details_dir+'/${objectname}_interface_contacts.txt');
+	voronota_export_adjuncts_of_contacts('-inter-residue', '-adjuncts', 'area', '-contacts-use', '[adjacent_to_iface]', '-file', params.details_dir+'/${objectname}_interface_and_adjacent_contacts.txt');
+}
+
 writeln(iface_cadscore);
-writeln(iface_cadscore_site_based);
 writeln(adjacent_to_iface_cadscore);
 EOF
 } \
