Added naming options in ligand cadscore script.

diff --git a/expansion_js/voronota-js-ligand-cadscore b/expansion_js/voronota-js-ligand-cadscore
--- a/expansion_js/voronota-js-ligand-cadscore
+++ b/expansion_js/voronota-js-ligand-cadscore
@@ -13,6 +13,8 @@ Input options, basic:
     --model-receptor              string  *  model receptor file path
     --model-ligands               string  *  list of model ligand file paths
     --model-ligand-ids            string  *  list of model ligand IDs
+    --target-name                 string     target to use for output, default is 'target_complex'
+    --model-name                  string     model name to use for output, default is 'model_complex'
 
 Input options, alternative:
     --casp15-target               string  *  target data file in CASP15 format, alternative to --target-* options
@@ -63,6 +65,8 @@ TARGET_LIGAND_IDS=""
 MODEL_RECEPTOR=""
 MODEL_LIGANDS=""
 MODEL_LIGAND_IDS=""
+TARGET_NAME="target_complex"
+MODEL_NAME="model_complex"
 CASP15_TARGET=""
 CASP15_TARGET_POSE=""
 CASP15_MODEL=""
@@ -99,6 +103,14 @@ do
 		;;
 	--model-ligand-ids)
 		MODEL_LIGAND_IDS="$OPTARG"
+		shift
+		;;
+	--target-name)
+		TARGET_NAME="$OPTARG"
+		shift
+		;;
+	--model-name)
+		MODEL_NAME="$OPTARG"
 		shift
 		;;
 	--casp15-target)
@@ -229,6 +241,7 @@ EOF
 	voronota-js-ligand-cadscore \
 	  --target-receptor "${TMPLDIR}/target_receptor.pdb" --target-ligands "$(cat ${TMPLDIR}/target_list)" --target-ligand-ids "$(cat ${TMPLDIR}/target_list_ids)" \
       --model-receptor "${TMPLDIR}/model_receptor.pdb" --model-ligands "$(cat ${TMPLDIR}/model_list)" --model-ligand-ids "$(cat ${TMPLDIR}/model_list_ids)" \
+      --target-name "$(basename ${CASP15_TARGET})_pose${CASP15_TARGET_POSE}" --model-name "$(basename ${CASP15_MODEL})_pose${CASP15_MODEL_POSE}" \
       --details-dir "$DETAILS_DIR" --drawing-dir "$DRAWING_DIR"
 	
 	exit 0
@@ -264,6 +277,22 @@ do
 	fi
 done < <(echo "${MODEL_LIGANDS}" | tr ' ' '\n' | egrep .)
 
+if [ -z "$TARGET_NAME" ]
+then
+	TARGET_NAME="target_complex"
+fi
+
+if [ -z "$MODEL_NAME" ]
+then
+	MODEL_NAME="model_complex"
+fi
+
+if [ "$TARGET_NAME" == "$MODEL_NAME" ]
+then
+	echo >&2 "Error: target and model are named the same"
+	exit 1
+fi
+
 if [ -n "$DETAILS_DIR" ]
 then
 	mkdir -p "$DETAILS_DIR"
@@ -291,6 +320,8 @@ params.target_receptor='$TARGET_RECEPTOR';
 params.target_ligands=[];
 params.model_receptor='$MODEL_RECEPTOR';
 params.model_ligands=[];
+params.target_name='$TARGET_NAME';
+params.model_name='$MODEL_NAME';
 params.details_dir='$DETAILS_DIR';
 params.details_dir=params.details_dir.trim();
 params.drawing_dir='$DRAWING_DIR';
@@ -349,10 +380,10 @@ for(var i=0;i<params.model_ligands.length;i++)
 
 voronota_unpick_objects();
 
-voronota_merge_objects('-names', target_object_names, '-title', 'target_complex');
-voronota_merge_objects('-names', model_object_names, '-title', 'model_complex');
+voronota_merge_objects('-names', target_object_names, '-title', params.target_name);
+voronota_merge_objects('-names', model_object_names, '-title', params.model_name);
 
-voronota_pick_objects('-names', ['target_complex', 'model_complex']);
+voronota_pick_objects('-names', [params.target_name, params.model_name]);
 voronota_delete_objects('-not-picked');
 voronota_set_atom_serials();
 
@@ -368,10 +399,10 @@ voronota_select_contacts('-use', '[-a1 [-t receptor|ligand] -a2 [-t ligand] -min
 voronota_select_atoms('-use', '[-sel-of-contacts iface]', '-full-residues', '-name', 'iface_atoms');
 voronota_select_contacts('-use', '[-a1 [iface_atoms] -a2 [iface_atoms] -min-seq-sep 1]', '-name', 'adjacent_to_iface');
 
-voronota_cad_score('-target', 'target_complex', '-model', 'model_complex', '-t-sel', '[iface]', '-m-sel', '[iface]');
+voronota_cad_score('-target', params.target_name, '-model', params.model_name, '-t-sel', '[iface]', '-m-sel', '[iface]');
 iface_cadscore=voronota_last_output().results[0].output.residue_level_result;
 
-voronota_cad_score('-target', 'target_complex', '-model', 'model_complex', '-t-sel', '[adjacent_to_iface]', '-m-sel', '[adjacent_to_iface]');
+voronota_cad_score('-target', params.target_name, '-model', params.model_name, '-t-sel', '[adjacent_to_iface]', '-m-sel', '[adjacent_to_iface]');
 adjacent_to_iface_cadscore=voronota_last_output().results[0].output.residue_level_result;
 
 writeln(iface_cadscore);
@@ -386,15 +417,17 @@ if(params.details_dir.length>0)
 if(params.drawing_dir.length>0)
 {
 	voronota_show_contacts('-use', '[adjacent_to_iface]');
-	voronota_spectrum_contacts('-use', '[adjacent_to_iface]', '-by', 'residue-ids', '-scheme', 'random');
-	//voronota_color_contacts('-use', '[adjacent_to_iface]', '-col', 'yellow');
-	//voronota_color_contacts('-use', '[iface]', '-col', 'green');
+	//voronota_spectrum_contacts('-use', '[adjacent_to_iface]', '-by', 'residue-ids', '-scheme', 'random');
+	voronota_color_contacts('-use', '[adjacent_to_iface]', '-col', 'yellow');
+	voronota_color_contacts('-use', '[iface]', '-col', 'green');
 	voronota_export_contacts_as_pymol_cgo('-use', '[iface]', '-file', params.drawing_dir+'/draw_${objectname}_interface_contacts_in_pymol.py', '-name', '${objectname}_interface_contacts');
 	voronota_export_contacts_as_pymol_cgo('-use', '[adjacent_to_iface]', '-file', params.drawing_dir+'/draw_${objectname}_interface_and_adjacent_contacts_in_pymol.py', '-name', '${objectname}_interface_and_adjacent_contacts');
-		
-	voronota_copy_object('target_complex', 'target_complex_cutout');
-	voronota_copy_object('model_complex', 'model_complex_cutout');
-	voronota_pick_objects('-names', ['target_complex_cutout', 'model_complex_cutout']);
+	
+	var target_cutout_name=params.target_name+'_cutout';
+	var model_cutout_name=params.model_name+'_cutout';
+	voronota_copy_object(params.target_name, target_cutout_name);
+	voronota_copy_object(params.model_name, model_cutout_name);
+	voronota_pick_objects('-names', [target_cutout_name, model_cutout_name]);
 	voronota_restrict_atoms('-use', '[iface_atoms]');
 	voronota_set_chain_name('-use', '[-t ligand]', '-chain-name', 'l');
 	voronota_set_atom_serials();
