Simplified relaxation helper script.

diff --git a/expansion_js/voronota-js-focused-relax-with-openmm b/expansion_js/voronota-js-focused-relax-with-openmm
--- a/expansion_js/voronota-js-focused-relax-with-openmm
+++ b/expansion_js/voronota-js-focused-relax-with-openmm
@@ -12,10 +12,9 @@ Options:
     --focus                   string     focus mode, default is "interface_side_chains", others are: "whole_interface", "not_interface", "whole_structure"
     --conda-path              string     conda installation path, default is ~/anaconda3
     --conda-env               string     conda environment name, default is alphafold2
-    --run-faspr               string     path to FASPR binary to rebuild side-chains
     --forcefield              string     forcefield name, default is "amber99sb.xml','amber99_obc", some others are: "amber14-all", "charmm36", "amber99sb"
     --max-iterations          number     max number of iterations, default is 100
-    --pdbfixer                           flag to run PDBFixer before everything
+    --no-preparation                     flag to not run PDBFixer and to not add hydrogens
     --help | -h                          flag to display help message and exit
 
 Standard output:
@@ -51,10 +50,9 @@ OUTFILE=""
 FOCUS_MODE="interface_side_chains"
 CONDA_PATH="${HOME}/anaconda3"
 CONDA_ENV="alphafold2"
-RUN_FASPR=""
 FORCEFIELD="amber99sb.xml','amber99_obc"
 MAX_ITERATIONS="100"
-WITH_PDBFIXER="false"
+NO_PREPARATION="false"
 HELP_MODE="false"
 
 while [[ $# > 0 ]]
@@ -83,10 +81,6 @@ do
 		CONDA_ENV="$OPTARG"
 		shift
 		;;
-	--run-faspr)
-		RUN_FASPR="$OPTARG"
-		shift
-		;;
 	--forcefield)
 		FORCEFIELD="$OPTARG"
 		shift
@@ -95,8 +89,8 @@ do
 		MAX_ITERATIONS="$OPTARG"
 		shift
 		;;
-	--pdbfixer)
-		WITH_PDBFIXER="true"
+	--no-preparation)
+		NO_PREPARATION="true"
 		;;
 	-h|--help)
 		HELP_MODE="true"
@@ -165,102 +159,47 @@ cp "$INFILE" "$TMPLDIR/input.pdb"
 
 cd "$TMPLDIR"
 
-if [ -n "$RUN_FASPR" ]
+if [ "$NO_PREPARATION" == "true" ]
 then
-	{
-cat << 'EOF'
-voronota_import("-file", "input.pdb");
-voronota_assert_partial_success("Failed to import file");
-
-voronota_run_faspr("-faspr-binary", 'RUN_FASPR');
-voronota_assert_full_success("Failed to run FASPR");
-
-voronota_export_atoms("-as-pdb", "-file", "prepared_initially.pdb");
-voronota_assert_full_success("Failed to export annotated atoms");
-EOF
-	} \
-	| sed "s|RUN_FASPR|${RUN_FASPR}|" \
-	> runfaspr.vs
-
-	echo >&2 "Running FASPR from voronota-js"
-	time -p voronota-js --no-setup-defaults < runfaspr.vs
+	cp "input.pdb" "prepared.pdb"
 else
-	cp "input.pdb" "prepared_initially.pdb"
-fi
-
-if [ ! -s "prepared_initially.pdb" ]
-then
-	echo >&2 "Error: failed to prepare input"
-	exit 1
-fi
-
-{
-cat << 'EOF'
-voronota_import("-file", "prepared_initially.pdb", "-include-hydrogens");
-voronota_assert_partial_success("Failed to import file");
-voronota_export_atoms("-as-pdb", "-file", "prepared_by_filtering.pdb");
-voronota_assert_full_success("Failed to export atoms");
-EOF
-} \
-> filter.vs
-
-echo >&2 "Filtering structure with voronota-js"
-time -p voronota-js --no-setup-defaults < filter.vs
-
-if [ ! -s "prepared_by_filtering.pdb" ]
-then
-	echo >&2 "Error: failed to prepare input"
-	exit 1
-fi
-
-{
+	{
 cat << 'EOF'
 from simtk.openmm.app import *
 from simtk.openmm import *
 from simtk.unit import *
-EOF
-
-if [ "$WITH_PDBFIXER" == "true" ]
-then
-cat << 'EOF'
 from pdbfixer import PDBFixer
-fixer = PDBFixer(filename='prepared_by_filtering.pdb')
+fixer = PDBFixer(filename='input.pdb')
 fixer.findMissingResidues()
 fixer.findNonstandardResidues()
 fixer.replaceNonstandardResidues()
-fixer.removeHeterogens(True)
+fixer.removeHeterogens(keepWater=False)
 fixer.findMissingAtoms()
 fixer.addMissingAtoms()
 modeller = Modeller(fixer.topology, fixer.positions)
-EOF
-else
-cat << 'EOF'
-pdb = PDBFile('prepared_by_filtering.pdb')
-modeller = Modeller(pdb.topology, pdb.positions)
-EOF
-fi
-
-cat << 'EOF'
 forcefield = ForceField('FORCEFIELD.xml')
 modeller.addHydrogens(forcefield)
-PDBFile.writeFile(modeller.topology, modeller.positions, open('prepared_with_simtk.pdb', 'w'), keepIds=True)
+PDBFile.writeFile(modeller.topology, modeller.positions, open('prepared.pdb', 'w'), keepIds=True)
 EOF
-} \
-| sed "s|FORCEFIELD|${FORCEFIELD}|" \
-> prepare.py
+	} \
+	| sed "s|FORCEFIELD|${FORCEFIELD}|" \
+	> prepare.py
+	
+	echo >&2 "Prepare structure file with simtk modeller"
+	time -p python prepare.py
+fi
 
-echo >&2 "Prepare structure file with simtk modeller"
-time -p python prepare.py
-
-if [ ! -s "prepared_with_simtk.pdb" ]
+if [ ! -s "prepared.pdb" ]
 then
 	echo >&2 "Error: failed to prepare input"
 	exit 1
 fi
 
-{
+if [ "$FOCUS_MODE" != "whole_structure" ]
+then
+	{
 cat << 'EOF'
-voronota_import("-file", "prepared_with_simtk.pdb", "-include-hydrogens", "-include-heteroatoms");
+voronota_import("-file", "prepared.pdb", "-include-hydrogens", "-include-heteroatoms");
 voronota_assert_partial_success("Failed to import file");
 
 voronota_select_atoms_close_to_interchain_interface("-name", "actii");
@@ -281,20 +220,20 @@ voronota_assert_full_success("Failed to tag atoms");
 voronota_export_atoms("-file", "annotated.pa");
 voronota_assert_full_success("Failed to export annotated atoms");
 EOF
+	} \
+	> annotate.vs
 
-} \
-> annotate.vs
-
-echo >&2 "Annotating structure with voronota-js"
-time -p voronota-js --no-setup-defaults < annotate.vs
-
-if [ ! -f "annotated.pa" ]
-then
-	echo >&2 "Error: failed to annotate input"
-	exit 1
+	echo >&2 "Annotating structure with voronota-js"
+	time -p voronota-js --no-setup-defaults < annotate.vs
+	
+	if [ ! -f "annotated.pa" ]
+	then
+		echo >&2 "Error: failed to annotate input"
+		exit 1
+	fi
+	
+	cat annotated.pa | awk '{print (NR-1) " " $0}' | grep -v "$FOCUS_MODE" | awk '{print "system.setParticleMass(" $1 ", 0.0)"}' > freezing.py
 fi
-
-cat annotated.pa | awk '{print (NR-1) " " $0}' | grep -v "$FOCUS_MODE" | awk '{print "system.setParticleMass(" $1 ", 0.0)"}' > freezing.py
 
 {
 cat << 'EOF'
@@ -302,12 +241,15 @@ from simtk.openmm.app import *
 from simtk.openmm import *
 from simtk.unit import *
 
-pdb = PDBFile('prepared_with_simtk.pdb')
+pdb = PDBFile('prepared.pdb')
 forcefield = ForceField('FORCEFIELD.xml')
 system = forcefield.createSystem(pdb.topology)
 EOF
 
-cat freezing.py
+if [ "$FOCUS_MODE" != "whole_structure" ]
+then
+	cat freezing.py
+fi
 
 cat << 'EOF'
 integrator = VerletIntegrator(0.001*picoseconds)
