Improved scripting plugins dependencies checks.

diff --git a/scripting/plugins/v-analyze-adjuncts-of-atoms b/scripting/plugins/v-analyze-adjuncts-of-atoms
--- a/scripting/plugins/v-analyze-adjuncts-of-atoms
+++ b/scripting/plugins/v-analyze-adjuncts-of-atoms
@@ -22,6 +22,8 @@ exit 1
 
 v-test-env || { echo >&2 "Error: 'voronota-scripting-env' environment not valid"; exit 1; }
 
+command -v R &> /dev/null || { echo >&2 "Error: 'R' executable not in binaries path"; exit 1; }
+
 ATOMS="[]"
 RSCRIPT=""
 HELP_MODE=false
@@ -66,8 +68,6 @@ then
 	echo >&2 "Error: missing script"
 	exit 1
 fi
-
-command -v R &> /dev/null || { echo >&2 "Error: 'R' executable not in binaries path"; exit 1; }
 
 readonly TMPLDIR=$(mktemp -d)
 
diff --git a/scripting/plugins/v-fetch b/scripting/plugins/v-fetch
--- a/scripting/plugins/v-fetch
+++ b/scripting/plugins/v-fetch
@@ -18,6 +18,8 @@ exit 1
 
 v-test-env || { echo >&2 "Error: 'voronota-scripting-env' environment not valid"; exit 1; }
 
+command -v curl &> /dev/null || { echo >&2 "Error: 'curl' executable not in binaries path"; exit 1; }
+
 PDB_ID=""
 PDB_SELECTED_ASSEMBLY=1
 PDB_SELECTED_CONFORMER=1
@@ -80,7 +82,7 @@ curl "http://www.rcsb.org/pdb/rest/getEntityInfo?structureId=${PDB_ID}" > "$TMPL
 
 if [ ! -s "$TMPLDIR/pdbinfo" ]
 then
-	echo >&2 "Error: failed to get info for PDB ID '$PDBID'"
+	echo >&2 "Error: failed to get info for PDB ID '$PDB_ID'"
 	exit 1
 fi
 
@@ -105,7 +107,7 @@ PDB_CHAINS="$(cat "$TMPLDIR/pdbinfo" \
 
 if [ "$PDB_ID_CONFIRMED" != "$PDB_ID" ]
 then
-	echo >&2 "Error: failed to get info for PDB ID '$PDBID'"
+	echo >&2 "Error: failed to get info for PDB ID '$PDB_ID'"
 	exit 1
 fi
 
diff --git a/scripting/plugins/v-save-image b/scripting/plugins/v-save-image
--- a/scripting/plugins/v-save-image
+++ b/scripting/plugins/v-save-image
@@ -15,6 +15,8 @@ exit 1
 
 v-test-env || { echo >&2 "Error: 'voronota-scripting-env' environment not valid"; exit 1; }
 
+command -v convert &> /dev/null || { echo >&2 "Error: 'convert' executable not in binaries path"; exit 1; }
+
 if [ "$V_GUI" != "true" ]
 then
 	echo >&2 "Error: Voronota not running in GUI mode"
@@ -54,8 +56,6 @@ then
 	echo >&2 "Error: missing output file path"
 	exit 1
 fi
-
-command -v convert &> /dev/null || { echo >&2 "Error: 'convert' executable not in binaries path"; exit 1; }
 
 readonly TMPLDIR=$(mktemp -d)
 
diff --git a/scripting/plugins/v-save-rotation-movie b/scripting/plugins/v-save-rotation-movie
--- a/scripting/plugins/v-save-rotation-movie
+++ b/scripting/plugins/v-save-rotation-movie
@@ -19,6 +19,8 @@ exit 1
 
 v-test-env || { echo >&2 "Error: 'voronota-scripting-env' environment not valid"; exit 1; }
 
+command -v convert &> /dev/null || { echo >&2 "Error: 'convert' executable not in binaries path"; exit 1; }
+
 if [ "$V_GUI" != "true" ]
 then
 	echo >&2 "Error: Voronota not running in GUI mode"
@@ -100,8 +102,6 @@ then
 	echo >&2 "Error: invalid delay, must be in interval from 1 to 10"
 	exit 1
 fi
-
-command -v convert &> /dev/null || { echo >&2 "Error: 'convert' executable not in binaries path"; exit 1; }
 
 readonly TMPLDIR=$(mktemp -d)
 
diff --git a/scripting/plugins/v-scwrl b/scripting/plugins/v-scwrl
--- a/scripting/plugins/v-scwrl
+++ b/scripting/plugins/v-scwrl
@@ -16,6 +16,8 @@ exit 1
 
 v-test-env || { echo >&2 "Error: 'voronota-scripting-env' environment not valid"; exit 1; }
 
+command -v Scwrl4 &> /dev/null || { echo >&2 "Error: 'Scwrl4' executable not in binaries path"; exit 1; }
+
 SOURCE_NAME=""
 DESTINATION_NAME=""
 HELP_MODE=false
@@ -60,8 +62,6 @@ then
 	echo >&2 "Error: missing destination name"
 	exit 1
 fi
-
-command -v Scwrl4 &> /dev/null || { echo >&2 "Error: 'Scwrl4' executable not in binaries path"; exit 1; }
 
 v-do-silent "list-objects '$SOURCE_NAME'"
 
diff --git a/scripting/plugins/v-tmalign b/scripting/plugins/v-tmalign
--- a/scripting/plugins/v-tmalign
+++ b/scripting/plugins/v-tmalign
@@ -18,6 +18,8 @@ exit 1
 
 v-test-env || { echo >&2 "Error: 'voronota-scripting-env' environment not valid"; exit 1; }
 
+command -v TMalign &> /dev/null || { echo >&2 "Error: 'TMalign' executable not in binaries path"; exit 1; }
+
 TARGET_NAME=""
 MODEL_NAME=""
 TARGET_SEL="[]"
@@ -72,8 +74,6 @@ then
 	echo >&2 "Error: missing model name"
 	exit 1
 fi
-
-command -v TMalign &> /dev/null || { echo >&2 "Error: 'TMalign' executable not in binaries path"; exit 1; }
 
 v-do-silent  "list-objects '$TARGET_NAME'"
 
diff --git a/scripting/voronota-scripting-plugins b/scripting/voronota-scripting-plugins
--- a/scripting/voronota-scripting-plugins
+++ b/scripting/voronota-scripting-plugins
@@ -44,6 +44,8 @@ exit 1
 
 v-test-env || { echo >&2 "Error: 'voronota-scripting-env' environment not valid"; exit 1; }
 
+command -v curl &> /dev/null || { echo >&2 "Error: 'curl' executable not in binaries path"; exit 1; }
+
 PDB_ID=""
 PDB_SELECTED_ASSEMBLY=1
 PDB_SELECTED_CONFORMER=1
@@ -106,7 +108,7 @@ curl "http://www.rcsb.org/pdb/rest/getEntityInfo?structureId=${PDB_ID}" > "$TMPL
 
 if [ ! -s "$TMPLDIR/pdbinfo" ]
 then
-	echo >&2 "Error: failed to get info for PDB ID '$PDBID'"
+	echo >&2 "Error: failed to get info for PDB ID '$PDB_ID'"
 	exit 1
 fi
 
@@ -131,7 +133,7 @@ PDB_CHAINS="$(cat "$TMPLDIR/pdbinfo" \
 
 if [ "$PDB_ID_CONFIRMED" != "$PDB_ID" ]
 then
-	echo >&2 "Error: failed to get info for PDB ID '$PDBID'"
+	echo >&2 "Error: failed to get info for PDB ID '$PDB_ID'"
 	exit 1
 fi
 
@@ -213,6 +215,8 @@ exit 1
 
 v-test-env || { echo >&2 "Error: 'voronota-scripting-env' environment not valid"; exit 1; }
 
+command -v convert &> /dev/null || { echo >&2 "Error: 'convert' executable not in binaries path"; exit 1; }
+
 if [ "$V_GUI" != "true" ]
 then
 	echo >&2 "Error: Voronota not running in GUI mode"
@@ -252,8 +256,6 @@ then
 	echo >&2 "Error: missing output file path"
 	exit 1
 fi
-
-command -v convert &> /dev/null || { echo >&2 "Error: 'convert' executable not in binaries path"; exit 1; }
 
 readonly TMPLDIR=$(mktemp -d)
 
@@ -300,6 +302,8 @@ exit 1
 }
 
 v-test-env || { echo >&2 "Error: 'voronota-scripting-env' environment not valid"; exit 1; }
+
+command -v convert &> /dev/null || { echo >&2 "Error: 'convert' executable not in binaries path"; exit 1; }
 
 if [ "$V_GUI" != "true" ]
 then
@@ -382,8 +386,6 @@ then
 	echo >&2 "Error: invalid delay, must be in interval from 1 to 10"
 	exit 1
 fi
-
-command -v convert &> /dev/null || { echo >&2 "Error: 'convert' executable not in binaries path"; exit 1; }
 
 readonly TMPLDIR=$(mktemp -d)
 
@@ -485,6 +487,8 @@ exit 1
 
 v-test-env || { echo >&2 "Error: 'voronota-scripting-env' environment not valid"; exit 1; }
 
+command -v TMalign &> /dev/null || { echo >&2 "Error: 'TMalign' executable not in binaries path"; exit 1; }
+
 TARGET_NAME=""
 MODEL_NAME=""
 TARGET_SEL="[]"
@@ -539,8 +543,6 @@ then
 	echo >&2 "Error: missing model name"
 	exit 1
 fi
-
-command -v TMalign &> /dev/null || { echo >&2 "Error: 'TMalign' executable not in binaries path"; exit 1; }
 
 v-do-silent  "list-objects '$TARGET_NAME'"
 
@@ -635,6 +637,8 @@ exit 1
 
 v-test-env || { echo >&2 "Error: 'voronota-scripting-env' environment not valid"; exit 1; }
 
+command -v Scwrl4 &> /dev/null || { echo >&2 "Error: 'Scwrl4' executable not in binaries path"; exit 1; }
+
 SOURCE_NAME=""
 DESTINATION_NAME=""
 HELP_MODE=false
@@ -679,8 +683,6 @@ then
 	echo >&2 "Error: missing destination name"
 	exit 1
 fi
-
-command -v Scwrl4 &> /dev/null || { echo >&2 "Error: 'Scwrl4' executable not in binaries path"; exit 1; }
 
 v-do-silent "list-objects '$SOURCE_NAME'"
 
@@ -748,6 +750,8 @@ exit 1
 
 v-test-env || { echo >&2 "Error: 'voronota-scripting-env' environment not valid"; exit 1; }
 
+command -v R &> /dev/null || { echo >&2 "Error: 'R' executable not in binaries path"; exit 1; }
+
 ATOMS="[]"
 RSCRIPT=""
 HELP_MODE=false
@@ -792,8 +796,6 @@ then
 	echo >&2 "Error: missing script"
 	exit 1
 fi
-
-command -v R &> /dev/null || { echo >&2 "Error: 'R' executable not in binaries path"; exit 1; }
 
 readonly TMPLDIR=$(mktemp -d)
 
